services:
  gosnag:
    build: .
    ports:
      - "8081:8080"
    env_file: .env
    restart: unless-stopped
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  dokploy-network:
    external: true
