// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countActivitiesByIssue = `-- name: CountActivitiesByIssue :one
SELECT count(*) FROM issue_activities WHERE issue_id = $1
`

func (q *Queries) CountActivitiesByIssue(ctx context.Context, issueID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivitiesByIssue, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO issue_activities (issue_id, ticket_id, user_id, action, old_value, new_value, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, issue_id, ticket_id, user_id, action, old_value, new_value, metadata, created_at
`

type InsertActivityParams struct {
	IssueID  uuid.UUID             `json:"issue_id"`
	TicketID uuid.NullUUID         `json:"ticket_id"`
	UserID   uuid.NullUUID         `json:"user_id"`
	Action   string                `json:"action"`
	OldValue sql.NullString        `json:"old_value"`
	NewValue sql.NullString        `json:"new_value"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (IssueActivity, error) {
	row := q.db.QueryRowContext(ctx, insertActivity,
		arg.IssueID,
		arg.TicketID,
		arg.UserID,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	var i IssueActivity
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TicketID,
		&i.UserID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivitiesByIssue = `-- name: ListActivitiesByIssue :many
SELECT a.id, a.issue_id, a.ticket_id, a.user_id, a.action, a.old_value, a.new_value, a.metadata, a.created_at, u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar
FROM issue_activities a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.issue_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivitiesByIssueParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListActivitiesByIssueRow struct {
	ID         uuid.UUID             `json:"id"`
	IssueID    uuid.UUID             `json:"issue_id"`
	TicketID   uuid.NullUUID         `json:"ticket_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	OldValue   sql.NullString        `json:"old_value"`
	NewValue   sql.NullString        `json:"new_value"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  time.Time             `json:"created_at"`
	UserName   sql.NullString        `json:"user_name"`
	UserEmail  sql.NullString        `json:"user_email"`
	UserAvatar sql.NullString        `json:"user_avatar"`
}

func (q *Queries) ListActivitiesByIssue(ctx context.Context, arg ListActivitiesByIssueParams) ([]ListActivitiesByIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByIssue, arg.IssueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesByIssueRow{}
	for rows.Next() {
		var i ListActivitiesByIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.TicketID,
			&i.UserID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
