// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAIAnalysis = `-- name: CreateAIAnalysis :one
INSERT INTO ai_analyses (issue_id, project_id, summary, evidence, suggested_fix, model, version)
VALUES ($1, $2, $3, $4, $5, $6,
    COALESCE((SELECT MAX(version) FROM ai_analyses WHERE issue_id = $1), 0) + 1
)
RETURNING id, issue_id, project_id, summary, evidence, suggested_fix, model, version, created_at
`

type CreateAIAnalysisParams struct {
	IssueID      uuid.UUID `json:"issue_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Summary      string    `json:"summary"`
	Evidence     string    `json:"evidence"`
	SuggestedFix string    `json:"suggested_fix"`
	Model        string    `json:"model"`
}

func (q *Queries) CreateAIAnalysis(ctx context.Context, arg CreateAIAnalysisParams) (AiAnalysis, error) {
	row := q.db.QueryRowContext(ctx, createAIAnalysis,
		arg.IssueID,
		arg.ProjectID,
		arg.Summary,
		arg.Evidence,
		arg.SuggestedFix,
		arg.Model,
	)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Summary,
		&i.Evidence,
		&i.SuggestedFix,
		&i.Model,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAIAnalysis = `-- name: GetLatestAIAnalysis :one
SELECT id, issue_id, project_id, summary, evidence, suggested_fix, model, version, created_at FROM ai_analyses
WHERE issue_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAIAnalysis(ctx context.Context, issueID uuid.UUID) (AiAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getLatestAIAnalysis, issueID)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Summary,
		&i.Evidence,
		&i.SuggestedFix,
		&i.Model,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listAIAnalyses = `-- name: ListAIAnalyses :many
SELECT id, issue_id, project_id, summary, evidence, suggested_fix, model, version, created_at FROM ai_analyses
WHERE issue_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAIAnalyses(ctx context.Context, issueID uuid.UUID) ([]AiAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, listAIAnalyses, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiAnalysis{}
	for rows.Next() {
		var i AiAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProjectID,
			&i.Summary,
			&i.Evidence,
			&i.SuggestedFix,
			&i.Model,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
