// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_merge_suggestions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptMergeSuggestion = `-- name: AcceptMergeSuggestion :exec
UPDATE ai_merge_suggestions
SET status = 'accepted'
WHERE id = $1
`

func (q *Queries) AcceptMergeSuggestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, acceptMergeSuggestion, id)
	return err
}

const createMergeSuggestion = `-- name: CreateMergeSuggestion :one
INSERT INTO ai_merge_suggestions (issue_id, target_issue_id, project_id, confidence, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, issue_id, target_issue_id, project_id, confidence, reason, status, created_at
`

type CreateMergeSuggestionParams struct {
	IssueID       uuid.UUID `json:"issue_id"`
	TargetIssueID uuid.UUID `json:"target_issue_id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Confidence    float32   `json:"confidence"`
	Reason        string    `json:"reason"`
}

func (q *Queries) CreateMergeSuggestion(ctx context.Context, arg CreateMergeSuggestionParams) (AiMergeSuggestion, error) {
	row := q.db.QueryRowContext(ctx, createMergeSuggestion,
		arg.IssueID,
		arg.TargetIssueID,
		arg.ProjectID,
		arg.Confidence,
		arg.Reason,
	)
	var i AiMergeSuggestion
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TargetIssueID,
		&i.ProjectID,
		&i.Confidence,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const dismissMergeSuggestion = `-- name: DismissMergeSuggestion :exec
UPDATE ai_merge_suggestions
SET status = 'dismissed'
WHERE id = $1
`

func (q *Queries) DismissMergeSuggestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, dismissMergeSuggestion, id)
	return err
}

const dismissSuggestionsForIssue = `-- name: DismissSuggestionsForIssue :exec
UPDATE ai_merge_suggestions
SET status = 'dismissed'
WHERE (issue_id = $1 OR target_issue_id = $1)
  AND status = 'pending'
`

func (q *Queries) DismissSuggestionsForIssue(ctx context.Context, issueID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, dismissSuggestionsForIssue, issueID)
	return err
}

const getMergeSuggestionByID = `-- name: GetMergeSuggestionByID :one
SELECT id, issue_id, target_issue_id, project_id, confidence, reason, status, created_at FROM ai_merge_suggestions WHERE id = $1
`

func (q *Queries) GetMergeSuggestionByID(ctx context.Context, id uuid.UUID) (AiMergeSuggestion, error) {
	row := q.db.QueryRowContext(ctx, getMergeSuggestionByID, id)
	var i AiMergeSuggestion
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TargetIssueID,
		&i.ProjectID,
		&i.Confidence,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingMergeSuggestion = `-- name: GetPendingMergeSuggestion :one
SELECT s.id, s.issue_id, s.target_issue_id, s.project_id, s.confidence, s.reason, s.status, s.created_at, i.title AS target_issue_title
FROM ai_merge_suggestions s
JOIN issues i ON i.id = s.target_issue_id
WHERE s.issue_id = $1
  AND s.status = 'pending'
LIMIT 1
`

type GetPendingMergeSuggestionRow struct {
	ID               uuid.UUID `json:"id"`
	IssueID          uuid.UUID `json:"issue_id"`
	TargetIssueID    uuid.UUID `json:"target_issue_id"`
	ProjectID        uuid.UUID `json:"project_id"`
	Confidence       float32   `json:"confidence"`
	Reason           string    `json:"reason"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	TargetIssueTitle string    `json:"target_issue_title"`
}

func (q *Queries) GetPendingMergeSuggestion(ctx context.Context, issueID uuid.UUID) (GetPendingMergeSuggestionRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingMergeSuggestion, issueID)
	var i GetPendingMergeSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TargetIssueID,
		&i.ProjectID,
		&i.Confidence,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.TargetIssueTitle,
	)
	return i, err
}

const listIssuesWithPendingSuggestions = `-- name: ListIssuesWithPendingSuggestions :many
SELECT DISTINCT s.issue_id FROM ai_merge_suggestions s WHERE s.project_id = $1 AND s.status = 'pending'
UNION
SELECT DISTINCT s.target_issue_id FROM ai_merge_suggestions s WHERE s.project_id = $1 AND s.status = 'pending'
`

func (q *Queries) ListIssuesWithPendingSuggestions(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesWithPendingSuggestions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var issue_id uuid.UUID
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
