// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearExpiredAICache = `-- name: ClearExpiredAICache :exec
UPDATE ai_usage_log
SET cached_response = NULL
WHERE cached_response IS NOT NULL
  AND created_at < now() - interval '5 minutes'
`

func (q *Queries) ClearExpiredAICache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExpiredAICache)
	return err
}

const getCachedResponse = `-- name: GetCachedResponse :one
SELECT cached_response
FROM ai_usage_log
WHERE project_id = $1
  AND prompt_hash = $2
  AND cached_response IS NOT NULL
  AND created_at >= now() - interval '5 minutes'
ORDER BY created_at DESC
LIMIT 1
`

type GetCachedResponseParams struct {
	ProjectID  uuid.UUID      `json:"project_id"`
	PromptHash sql.NullString `json:"prompt_hash"`
}

func (q *Queries) GetCachedResponse(ctx context.Context, arg GetCachedResponseParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCachedResponse, arg.ProjectID, arg.PromptHash)
	var cached_response sql.NullString
	err := row.Scan(&cached_response)
	return cached_response, err
}

const getCallsInLastMinute = `-- name: GetCallsInLastMinute :one
SELECT COUNT(*)::bigint
FROM ai_usage_log
WHERE project_id = $1
  AND created_at >= now() - interval '1 minute'
`

func (q *Queries) GetCallsInLastMinute(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCallsInLastMinute, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDailyTokenUsage = `-- name: GetDailyTokenUsage :one
SELECT COALESCE(SUM(input_tokens + output_tokens), 0)::bigint
FROM ai_usage_log
WHERE project_id = $1
  AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC')
`

func (q *Queries) GetDailyTokenUsage(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDailyTokenUsage, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getProjectAIUsageToday = `-- name: GetProjectAIUsageToday :one
SELECT COALESCE(SUM(input_tokens + output_tokens), 0)::bigint AS total_tokens,
       COUNT(*)::bigint AS total_calls
FROM ai_usage_log
WHERE project_id = $1
  AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC')
`

type GetProjectAIUsageTodayRow struct {
	TotalTokens int64 `json:"total_tokens"`
	TotalCalls  int64 `json:"total_calls"`
}

func (q *Queries) GetProjectAIUsageToday(ctx context.Context, projectID uuid.UUID) (GetProjectAIUsageTodayRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectAIUsageToday, projectID)
	var i GetProjectAIUsageTodayRow
	err := row.Scan(&i.TotalTokens, &i.TotalCalls)
	return i, err
}

const getProjectAIUsageWeek = `-- name: GetProjectAIUsageWeek :one
SELECT COALESCE(SUM(input_tokens + output_tokens), 0)::bigint AS total_tokens,
       COUNT(*)::bigint AS total_calls
FROM ai_usage_log
WHERE project_id = $1
  AND created_at >= date_trunc('week', now() AT TIME ZONE 'UTC')
`

type GetProjectAIUsageWeekRow struct {
	TotalTokens int64 `json:"total_tokens"`
	TotalCalls  int64 `json:"total_calls"`
}

func (q *Queries) GetProjectAIUsageWeek(ctx context.Context, projectID uuid.UUID) (GetProjectAIUsageWeekRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectAIUsageWeek, projectID)
	var i GetProjectAIUsageWeekRow
	err := row.Scan(&i.TotalTokens, &i.TotalCalls)
	return i, err
}

const logAICall = `-- name: LogAICall :exec
INSERT INTO ai_usage_log (project_id, feature, model, input_tokens, output_tokens, latency_ms, prompt_hash, cached_response)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type LogAICallParams struct {
	ProjectID      uuid.UUID      `json:"project_id"`
	Feature        string         `json:"feature"`
	Model          string         `json:"model"`
	InputTokens    int32          `json:"input_tokens"`
	OutputTokens   int32          `json:"output_tokens"`
	LatencyMs      int32          `json:"latency_ms"`
	PromptHash     sql.NullString `json:"prompt_hash"`
	CachedResponse sql.NullString `json:"cached_response"`
}

func (q *Queries) LogAICall(ctx context.Context, arg LogAICallParams) error {
	_, err := q.db.ExecContext(ctx, logAICall,
		arg.ProjectID,
		arg.Feature,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.LatencyMs,
		arg.PromptHash,
		arg.CachedResponse,
	)
	return err
}
