// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAlertConfig = `-- name: CreateAlertConfig :one
INSERT INTO alert_configs (project_id, alert_type, config, enabled, level_filter, title_pattern, min_events, min_velocity_1h, exclude_pattern, conditions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern, min_events, min_velocity_1h, exclude_pattern, conditions
`

type CreateAlertConfigParams struct {
	ProjectID      uuid.UUID             `json:"project_id"`
	AlertType      string                `json:"alert_type"`
	Config         json.RawMessage       `json:"config"`
	Enabled        bool                  `json:"enabled"`
	LevelFilter    string                `json:"level_filter"`
	TitlePattern   string                `json:"title_pattern"`
	MinEvents      int32                 `json:"min_events"`
	MinVelocity1h  int32                 `json:"min_velocity_1h"`
	ExcludePattern string                `json:"exclude_pattern"`
	Conditions     pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) CreateAlertConfig(ctx context.Context, arg CreateAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, createAlertConfig,
		arg.ProjectID,
		arg.AlertType,
		arg.Config,
		arg.Enabled,
		arg.LevelFilter,
		arg.TitlePattern,
		arg.MinEvents,
		arg.MinVelocity1h,
		arg.ExcludePattern,
		arg.Conditions,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AlertType,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LevelFilter,
		&i.TitlePattern,
		&i.MinEvents,
		&i.MinVelocity1h,
		&i.ExcludePattern,
		&i.Conditions,
	)
	return i, err
}

const deleteAlertConfig = `-- name: DeleteAlertConfig :exec
DELETE FROM alert_configs WHERE id = $1 AND project_id = $2
`

type DeleteAlertConfigParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteAlertConfig(ctx context.Context, arg DeleteAlertConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlertConfig, arg.ID, arg.ProjectID)
	return err
}

const getEnabledAlerts = `-- name: GetEnabledAlerts :many
SELECT id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern, min_events, min_velocity_1h, exclude_pattern, conditions FROM alert_configs WHERE project_id = $1 AND enabled = true
`

func (q *Queries) GetEnabledAlerts(ctx context.Context, projectID uuid.UUID) ([]AlertConfig, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledAlerts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertConfig{}
	for rows.Next() {
		var i AlertConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AlertType,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LevelFilter,
			&i.TitlePattern,
			&i.MinEvents,
			&i.MinVelocity1h,
			&i.ExcludePattern,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertConfigs = `-- name: ListAlertConfigs :many
SELECT id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern, min_events, min_velocity_1h, exclude_pattern, conditions FROM alert_configs WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListAlertConfigs(ctx context.Context, projectID uuid.UUID) ([]AlertConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAlertConfigs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertConfig{}
	for rows.Next() {
		var i AlertConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AlertType,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LevelFilter,
			&i.TitlePattern,
			&i.MinEvents,
			&i.MinVelocity1h,
			&i.ExcludePattern,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertConfig = `-- name: UpdateAlertConfig :one
UPDATE alert_configs
SET config = $3, enabled = $4, level_filter = $5, title_pattern = $6, min_events = $7, min_velocity_1h = $8, exclude_pattern = $9, conditions = $10, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern, min_events, min_velocity_1h, exclude_pattern, conditions
`

type UpdateAlertConfigParams struct {
	ID             uuid.UUID             `json:"id"`
	ProjectID      uuid.UUID             `json:"project_id"`
	Config         json.RawMessage       `json:"config"`
	Enabled        bool                  `json:"enabled"`
	LevelFilter    string                `json:"level_filter"`
	TitlePattern   string                `json:"title_pattern"`
	MinEvents      int32                 `json:"min_events"`
	MinVelocity1h  int32                 `json:"min_velocity_1h"`
	ExcludePattern string                `json:"exclude_pattern"`
	Conditions     pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) UpdateAlertConfig(ctx context.Context, arg UpdateAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, updateAlertConfig,
		arg.ID,
		arg.ProjectID,
		arg.Config,
		arg.Enabled,
		arg.LevelFilter,
		arg.TitlePattern,
		arg.MinEvents,
		arg.MinVelocity1h,
		arg.ExcludePattern,
		arg.Conditions,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AlertType,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LevelFilter,
		&i.TitlePattern,
		&i.MinEvents,
		&i.MinVelocity1h,
		&i.ExcludePattern,
		&i.Conditions,
	)
	return i, err
}
