// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO ticket_attachments (ticket_id, filename, url, content_type, size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ticket_id, filename, url, content_type, size_bytes, uploaded_by, created_at
`

type CreateAttachmentParams struct {
	TicketID    uuid.UUID `json:"ticket_id"`
	Filename    string    `json:"filename"`
	Url         string    `json:"url"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (TicketAttachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.TicketID,
		arg.Filename,
		arg.Url,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i TicketAttachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Filename,
		&i.Url,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM ticket_attachments WHERE id = $1 AND ticket_id = $2
`

type DeleteAttachmentParams struct {
	ID       uuid.UUID `json:"id"`
	TicketID uuid.UUID `json:"ticket_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.TicketID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, ticket_id, filename, url, content_type, size_bytes, uploaded_by, created_at FROM ticket_attachments WHERE id = $1 AND ticket_id = $2
`

type GetAttachmentParams struct {
	ID       uuid.UUID `json:"id"`
	TicketID uuid.UUID `json:"ticket_id"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (TicketAttachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, arg.ID, arg.TicketID)
	var i TicketAttachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Filename,
		&i.Url,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByTicket = `-- name: ListAttachmentsByTicket :many
SELECT a.id, a.ticket_id, a.filename, a.url, a.content_type, a.size_bytes, a.uploaded_by, a.created_at, u.name AS uploader_name, u.email AS uploader_email
FROM ticket_attachments a
JOIN users u ON u.id = a.uploaded_by
WHERE a.ticket_id = $1
ORDER BY a.created_at
`

type ListAttachmentsByTicketRow struct {
	ID            uuid.UUID `json:"id"`
	TicketID      uuid.UUID `json:"ticket_id"`
	Filename      string    `json:"filename"`
	Url           string    `json:"url"`
	ContentType   string    `json:"content_type"`
	SizeBytes     int64     `json:"size_bytes"`
	UploadedBy    uuid.UUID `json:"uploaded_by"`
	CreatedAt     time.Time `json:"created_at"`
	UploaderName  string    `json:"uploader_name"`
	UploaderEmail string    `json:"uploader_email"`
}

func (q *Queries) ListAttachmentsByTicket(ctx context.Context, ticketID uuid.UUID) ([]ListAttachmentsByTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsByTicketRow{}
	for rows.Next() {
		var i ListAttachmentsByTicketRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Filename,
			&i.Url,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UploaderName,
			&i.UploaderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
