// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploy_analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDeployAnalysis = `-- name: CreateDeployAnalysis :one
INSERT INTO deploy_analyses (deploy_id, project_id, severity, summary, details, likely_deploy_caused, recommended_action, new_issues_count, spiked_issues_count, reopened_issues_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, deploy_id, project_id, severity, summary, details, likely_deploy_caused, recommended_action, new_issues_count, spiked_issues_count, reopened_issues_count, created_at
`

type CreateDeployAnalysisParams struct {
	DeployID            uuid.UUID `json:"deploy_id"`
	ProjectID           uuid.UUID `json:"project_id"`
	Severity            string    `json:"severity"`
	Summary             string    `json:"summary"`
	Details             string    `json:"details"`
	LikelyDeployCaused  bool      `json:"likely_deploy_caused"`
	RecommendedAction   string    `json:"recommended_action"`
	NewIssuesCount      int32     `json:"new_issues_count"`
	SpikedIssuesCount   int32     `json:"spiked_issues_count"`
	ReopenedIssuesCount int32     `json:"reopened_issues_count"`
}

func (q *Queries) CreateDeployAnalysis(ctx context.Context, arg CreateDeployAnalysisParams) (DeployAnalysis, error) {
	row := q.db.QueryRowContext(ctx, createDeployAnalysis,
		arg.DeployID,
		arg.ProjectID,
		arg.Severity,
		arg.Summary,
		arg.Details,
		arg.LikelyDeployCaused,
		arg.RecommendedAction,
		arg.NewIssuesCount,
		arg.SpikedIssuesCount,
		arg.ReopenedIssuesCount,
	)
	var i DeployAnalysis
	err := row.Scan(
		&i.ID,
		&i.DeployID,
		&i.ProjectID,
		&i.Severity,
		&i.Summary,
		&i.Details,
		&i.LikelyDeployCaused,
		&i.RecommendedAction,
		&i.NewIssuesCount,
		&i.SpikedIssuesCount,
		&i.ReopenedIssuesCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeployAnalysis = `-- name: DeleteDeployAnalysis :exec
DELETE FROM deploy_analyses WHERE deploy_id = $1
`

func (q *Queries) DeleteDeployAnalysis(ctx context.Context, deployID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeployAnalysis, deployID)
	return err
}

const getDeployAnalysis = `-- name: GetDeployAnalysis :one
SELECT id, deploy_id, project_id, severity, summary, details, likely_deploy_caused, recommended_action, new_issues_count, spiked_issues_count, reopened_issues_count, created_at FROM deploy_analyses WHERE deploy_id = $1
`

func (q *Queries) GetDeployAnalysis(ctx context.Context, deployID uuid.UUID) (DeployAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getDeployAnalysis, deployID)
	var i DeployAnalysis
	err := row.Scan(
		&i.ID,
		&i.DeployID,
		&i.ProjectID,
		&i.Severity,
		&i.Summary,
		&i.Details,
		&i.LikelyDeployCaused,
		&i.RecommendedAction,
		&i.NewIssuesCount,
		&i.SpikedIssuesCount,
		&i.ReopenedIssuesCount,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDeployAnalysisByProject = `-- name: GetLatestDeployAnalysisByProject :one
SELECT id, deploy_id, project_id, severity, summary, details, likely_deploy_caused, recommended_action, new_issues_count, spiked_issues_count, reopened_issues_count, created_at FROM deploy_analyses WHERE project_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestDeployAnalysisByProject(ctx context.Context, projectID uuid.UUID) (DeployAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeployAnalysisByProject, projectID)
	var i DeployAnalysis
	err := row.Scan(
		&i.ID,
		&i.DeployID,
		&i.ProjectID,
		&i.Severity,
		&i.Summary,
		&i.Details,
		&i.LikelyDeployCaused,
		&i.RecommendedAction,
		&i.NewIssuesCount,
		&i.SpikedIssuesCount,
		&i.ReopenedIssuesCount,
		&i.CreatedAt,
	)
	return i, err
}

const listDeployAnalysesByProject = `-- name: ListDeployAnalysesByProject :many
SELECT id, deploy_id, project_id, severity, summary, details, likely_deploy_caused, recommended_action, new_issues_count, spiked_issues_count, reopened_issues_count, created_at FROM deploy_analyses WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListDeployAnalysesByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListDeployAnalysesByProject(ctx context.Context, arg ListDeployAnalysesByProjectParams) ([]DeployAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, listDeployAnalysesByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployAnalysis{}
	for rows.Next() {
		var i DeployAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.DeployID,
			&i.ProjectID,
			&i.Severity,
			&i.Summary,
			&i.Details,
			&i.LikelyDeployCaused,
			&i.RecommendedAction,
			&i.NewIssuesCount,
			&i.SpikedIssuesCount,
			&i.ReopenedIssuesCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
