// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countEventsByIssue = `-- name: CountEventsByIssue :one
SELECT count(*) FROM events WHERE issue_id = $1
`

func (q *Queries) CountEventsByIssue(ctx context.Context, issueID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByIssue, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsInWindow = `-- name: CountEventsInWindow :one
SELECT count(*) FROM events WHERE project_id = $1 AND timestamp >= $2 AND timestamp < $3
`

type CountEventsInWindowParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Timestamp   time.Time `json:"timestamp"`
	Timestamp_2 time.Time `json:"timestamp_2"`
}

func (q *Queries) CountEventsInWindow(ctx context.Context, arg CountEventsInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsInWindow, arg.ProjectID, arg.Timestamp, arg.Timestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsPerIssueInWindow = `-- name: CountEventsPerIssueInWindow :many
SELECT issue_id, count(*)::int as event_count
FROM events
WHERE project_id = $1 AND timestamp >= $2 AND timestamp < $3
GROUP BY issue_id
`

type CountEventsPerIssueInWindowParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Timestamp   time.Time `json:"timestamp"`
	Timestamp_2 time.Time `json:"timestamp_2"`
}

type CountEventsPerIssueInWindowRow struct {
	IssueID    uuid.UUID `json:"issue_id"`
	EventCount int32     `json:"event_count"`
}

func (q *Queries) CountEventsPerIssueInWindow(ctx context.Context, arg CountEventsPerIssueInWindowParams) ([]CountEventsPerIssueInWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, countEventsPerIssueInWindow, arg.ProjectID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsPerIssueInWindowRow{}
	for rows.Next() {
		var i CountEventsPerIssueInWindowRow
		if err := rows.Scan(&i.IssueID, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (issue_id, project_id, event_id, timestamp, platform, level, message, release, environment, server_name, data, user_identifier)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, issue_id, project_id, event_id, timestamp, platform, level, message, release, environment, server_name, data, created_at, user_identifier
`

type CreateEventParams struct {
	IssueID        uuid.UUID       `json:"issue_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	EventID        string          `json:"event_id"`
	Timestamp      time.Time       `json:"timestamp"`
	Platform       string          `json:"platform"`
	Level          string          `json:"level"`
	Message        string          `json:"message"`
	Release        string          `json:"release"`
	Environment    string          `json:"environment"`
	ServerName     string          `json:"server_name"`
	Data           json.RawMessage `json:"data"`
	UserIdentifier string          `json:"user_identifier"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.IssueID,
		arg.ProjectID,
		arg.EventID,
		arg.Timestamp,
		arg.Platform,
		arg.Level,
		arg.Message,
		arg.Release,
		arg.Environment,
		arg.ServerName,
		arg.Data,
		arg.UserIdentifier,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.EventID,
		&i.Timestamp,
		&i.Platform,
		&i.Level,
		&i.Message,
		&i.Release,
		&i.Environment,
		&i.ServerName,
		&i.Data,
		&i.CreatedAt,
		&i.UserIdentifier,
	)
	return i, err
}

const deleteEventsOlderThan = `-- name: DeleteEventsOlderThan :execresult
DELETE FROM events WHERE created_at < $1
`

func (q *Queries) DeleteEventsOlderThan(ctx context.Context, createdAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEventsOlderThan, createdAt)
}

const getEvent = `-- name: GetEvent :one
SELECT id, issue_id, project_id, event_id, timestamp, platform, level, message, release, environment, server_name, data, created_at, user_identifier FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.EventID,
		&i.Timestamp,
		&i.Platform,
		&i.Level,
		&i.Message,
		&i.Release,
		&i.Environment,
		&i.ServerName,
		&i.Data,
		&i.CreatedAt,
		&i.UserIdentifier,
	)
	return i, err
}

const getEventTrendByIssues = `-- name: GetEventTrendByIssues :many
SELECT issue_id,
       date_trunc('hour', timestamp)::timestamptz as bucket,
       COUNT(*)::int as count
FROM events
WHERE issue_id = ANY($1::uuid[])
  AND timestamp >= now() - interval '24 hours'
GROUP BY issue_id, bucket
ORDER BY issue_id, bucket
`

type GetEventTrendByIssuesRow struct {
	IssueID uuid.UUID `json:"issue_id"`
	Bucket  time.Time `json:"bucket"`
	Count   int32     `json:"count"`
}

func (q *Queries) GetEventTrendByIssues(ctx context.Context, dollar_1 []uuid.UUID) ([]GetEventTrendByIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventTrendByIssues, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventTrendByIssuesRow{}
	for rows.Next() {
		var i GetEventTrendByIssuesRow
		if err := rows.Scan(&i.IssueID, &i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssueUserCount = `-- name: GetIssueUserCount :one
SELECT COUNT(DISTINCT user_identifier)::int as user_count
FROM events
WHERE issue_id = $1 AND user_identifier != ''
`

func (q *Queries) GetIssueUserCount(ctx context.Context, issueID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getIssueUserCount, issueID)
	var user_count int32
	err := row.Scan(&user_count)
	return user_count, err
}

const getLatestEventByIssue = `-- name: GetLatestEventByIssue :one
SELECT id, issue_id, project_id, event_id, timestamp, platform, level, message, release, environment, server_name, data, created_at, user_identifier FROM events
WHERE issue_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestEventByIssue(ctx context.Context, issueID uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getLatestEventByIssue, issueID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.EventID,
		&i.Timestamp,
		&i.Platform,
		&i.Level,
		&i.Message,
		&i.Release,
		&i.Environment,
		&i.ServerName,
		&i.Data,
		&i.CreatedAt,
		&i.UserIdentifier,
	)
	return i, err
}

const getUniqueUserCountsByIssues = `-- name: GetUniqueUserCountsByIssues :many
SELECT issue_id, COUNT(DISTINCT user_identifier)::int as user_count
FROM events
WHERE issue_id = ANY($1::uuid[])
  AND user_identifier != ''
GROUP BY issue_id
`

type GetUniqueUserCountsByIssuesRow struct {
	IssueID   uuid.UUID `json:"issue_id"`
	UserCount int32     `json:"user_count"`
}

func (q *Queries) GetUniqueUserCountsByIssues(ctx context.Context, dollar_1 []uuid.UUID) ([]GetUniqueUserCountsByIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUniqueUserCountsByIssues, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUniqueUserCountsByIssuesRow{}
	for rows.Next() {
		var i GetUniqueUserCountsByIssuesRow
		if err := rows.Scan(&i.IssueID, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByIssue = `-- name: ListEventsByIssue :many
SELECT id, issue_id, project_id, event_id, timestamp, platform, level, message, release, environment, server_name, data, created_at, user_identifier FROM events
WHERE issue_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListEventsByIssueParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListEventsByIssue(ctx context.Context, arg ListEventsByIssueParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByIssue, arg.IssueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProjectID,
			&i.EventID,
			&i.Timestamp,
			&i.Platform,
			&i.Level,
			&i.Message,
			&i.Release,
			&i.Environment,
			&i.ServerName,
			&i.Data,
			&i.CreatedAt,
			&i.UserIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
