// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_rules.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createGithubRule = `-- name: CreateGithubRule :one
INSERT INTO github_rules (project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions, created_at, updated_at
`

type CreateGithubRuleParams struct {
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) CreateGithubRule(ctx context.Context, arg CreateGithubRuleParams) (GithubRule, error) {
	row := q.db.QueryRowContext(ctx, createGithubRule,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.LevelFilter,
		arg.MinEvents,
		arg.MinUsers,
		arg.TitlePattern,
		arg.Conditions,
	)
	var i GithubRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.Conditions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGithubRule = `-- name: DeleteGithubRule :exec
DELETE FROM github_rules WHERE id = $1 AND project_id = $2
`

type DeleteGithubRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteGithubRule(ctx context.Context, arg DeleteGithubRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteGithubRule, arg.ID, arg.ProjectID)
	return err
}

const getGithubRule = `-- name: GetGithubRule :one
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions, created_at, updated_at FROM github_rules WHERE id = $1
`

func (q *Queries) GetGithubRule(ctx context.Context, id uuid.UUID) (GithubRule, error) {
	row := q.db.QueryRowContext(ctx, getGithubRule, id)
	var i GithubRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.Conditions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledGithubRules = `-- name: ListEnabledGithubRules :many
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions, created_at, updated_at FROM github_rules WHERE project_id = $1 AND enabled = true
`

func (q *Queries) ListEnabledGithubRules(ctx context.Context, projectID uuid.UUID) ([]GithubRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledGithubRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRule{}
	for rows.Next() {
		var i GithubRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.LevelFilter,
			&i.MinEvents,
			&i.MinUsers,
			&i.TitlePattern,
			&i.Conditions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubRules = `-- name: ListGithubRules :many
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions, created_at, updated_at FROM github_rules WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListGithubRules(ctx context.Context, projectID uuid.UUID) ([]GithubRule, error) {
	rows, err := q.db.QueryContext(ctx, listGithubRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRule{}
	for rows.Next() {
		var i GithubRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.LevelFilter,
			&i.MinEvents,
			&i.MinUsers,
			&i.TitlePattern,
			&i.Conditions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGithubRule = `-- name: UpdateGithubRule :one
UPDATE github_rules
SET name = $3, enabled = $4, level_filter = $5, min_events = $6, min_users = $7, title_pattern = $8, conditions = $9, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions, created_at, updated_at
`

type UpdateGithubRuleParams struct {
	ID           uuid.UUID             `json:"id"`
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) UpdateGithubRule(ctx context.Context, arg UpdateGithubRuleParams) (GithubRule, error) {
	row := q.db.QueryRowContext(ctx, updateGithubRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.LevelFilter,
		arg.MinEvents,
		arg.MinUsers,
		arg.TitlePattern,
		arg.Conditions,
	)
	var i GithubRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.Conditions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueGithubTicket = `-- name: UpdateIssueGithubTicket :execresult
UPDATE issues SET github_issue_number = $2, github_issue_url = $3, updated_at = now()
WHERE id = $1 AND github_issue_number IS NULL
`

type UpdateIssueGithubTicketParams struct {
	ID                uuid.UUID      `json:"id"`
	GithubIssueNumber sql.NullInt32  `json:"github_issue_number"`
	GithubIssueUrl    sql.NullString `json:"github_issue_url"`
}

func (q *Queries) UpdateIssueGithubTicket(ctx context.Context, arg UpdateIssueGithubTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateIssueGithubTicket, arg.ID, arg.GithubIssueNumber, arg.GithubIssueUrl)
}
