// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignIssue = `-- name: AssignIssue :one
UPDATE issues
SET assigned_to = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url
`

type AssignIssueParams struct {
	ID         uuid.UUID     `json:"id"`
	AssignedTo uuid.NullUUID `json:"assigned_to"`
}

func (q *Queries) AssignIssue(ctx context.Context, arg AssignIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, assignIssue, arg.ID, arg.AssignedTo)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
		&i.FirstRelease,
		&i.GithubIssueNumber,
		&i.GithubIssueUrl,
	)
	return i, err
}

const countIssuesAssigned = `-- name: CountIssuesAssigned :one
SELECT count(*)::int FROM issues
WHERE project_id = $1
  AND assigned_to IS NOT NULL
  AND ($2::text = '' OR level = $2::text
    OR ($2::text = 'errors' AND level IN ('error', 'fatal'))
    OR ($2::text = 'errors_w' AND level IN ('error', 'fatal', 'warning'))
    OR ($2::text = 'informational' AND level IN ('warning', 'info', 'debug'))
    OR ($2::text = 'info_only' AND level IN ('info', 'debug')))
`

type CountIssuesAssignedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
}

func (q *Queries) CountIssuesAssigned(ctx context.Context, arg CountIssuesAssignedParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countIssuesAssigned, arg.ProjectID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countIssuesAssignedToUser = `-- name: CountIssuesAssignedToUser :one
SELECT count(*)::int FROM issues
WHERE project_id = $1
  AND assigned_to = $2
  AND ($3::text = '' OR level = $3::text
    OR ($3::text = 'errors' AND level IN ('error', 'fatal'))
    OR ($3::text = 'errors_w' AND level IN ('error', 'fatal', 'warning'))
    OR ($3::text = 'informational' AND level IN ('warning', 'info', 'debug'))
    OR ($3::text = 'info_only' AND level IN ('info', 'debug')))
`

type CountIssuesAssignedToUserParams struct {
	ProjectID  uuid.UUID     `json:"project_id"`
	AssignedTo uuid.NullUUID `json:"assigned_to"`
	Column3    string        `json:"column_3"`
}

func (q *Queries) CountIssuesAssignedToUser(ctx context.Context, arg CountIssuesAssignedToUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countIssuesAssignedToUser, arg.ProjectID, arg.AssignedTo, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countIssuesByProject = `-- name: CountIssuesByProject :one
SELECT count(*) FROM issues
WHERE project_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND (NOT $3::bool OR first_seen >= CURRENT_DATE)
  AND (NOT $4::bool OR assigned_to IS NOT NULL)
  AND ($5::uuid IS NULL OR assigned_to = $5)
  AND ($6::text = '' OR level = $6::text
    OR ($6::text = 'errors' AND level IN ('error', 'fatal'))
    OR ($6::text = 'errors_w' AND level IN ('error', 'fatal', 'warning'))
    OR ($6::text = 'informational' AND level IN ('warning', 'info', 'debug'))
    OR ($6::text = 'info_only' AND level IN ('info', 'debug')))
  AND ($7::text = '' OR title ILIKE '%' || $7::text || '%')
  AND ($8::text = '' OR first_release = $8::text)
`

type CountIssuesByProjectParams struct {
	ProjectID      uuid.UUID     `json:"project_id"`
	Column2        string        `json:"column_2"`
	Column3        bool          `json:"column_3"`
	Column4        bool          `json:"column_4"`
	AssignedToUser uuid.NullUUID `json:"assigned_to_user"`
	LevelFilter    string        `json:"level_filter"`
	Search         string        `json:"search"`
	ReleaseFilter  string        `json:"release_filter"`
}

func (q *Queries) CountIssuesByProject(ctx context.Context, arg CountIssuesByProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.AssignedToUser,
		arg.LevelFilter,
		arg.Search,
		arg.ReleaseFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesToday = `-- name: CountIssuesToday :one
SELECT count(*)::int FROM issues
WHERE project_id = $1
  AND first_seen >= CURRENT_DATE
  AND ($2::text = '' OR level = $2::text
    OR ($2::text = 'errors' AND level IN ('error', 'fatal'))
    OR ($2::text = 'errors_w' AND level IN ('error', 'fatal', 'warning'))
    OR ($2::text = 'informational' AND level IN ('warning', 'info', 'debug'))
    OR ($2::text = 'info_only' AND level IN ('info', 'debug')))
`

type CountIssuesTodayParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
}

func (q *Queries) CountIssuesToday(ctx context.Context, arg CountIssuesTodayParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countIssuesToday, arg.ProjectID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteIssues = `-- name: DeleteIssues :execresult
DELETE FROM issues WHERE id = ANY($1::uuid[]) AND project_id = $2
`

type DeleteIssuesParams struct {
	Ids       []uuid.UUID `json:"ids"`
	ProjectID uuid.UUID   `json:"project_id"`
}

func (q *Queries) DeleteIssues(ctx context.Context, arg DeleteIssuesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIssues, pq.Array(arg.Ids), arg.ProjectID)
}

const followIssue = `-- name: FollowIssue :exec
INSERT INTO issue_follows (user_id, issue_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type FollowIssueParams struct {
	UserID  uuid.UUID `json:"user_id"`
	IssueID uuid.UUID `json:"issue_id"`
}

func (q *Queries) FollowIssue(ctx context.Context, arg FollowIssueParams) error {
	_, err := q.db.ExecContext(ctx, followIssue, arg.UserID, arg.IssueID)
	return err
}

const getExpiredCooldownIssues = `-- name: GetExpiredCooldownIssues :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE status = 'resolved'
  AND cooldown_until IS NOT NULL
  AND cooldown_until < now()
`

func (q *Queries) GetExpiredCooldownIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredCooldownIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredSnoozeIssues = `-- name: GetExpiredSnoozeIssues :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE status = 'snoozed'
  AND snooze_until IS NOT NULL
  AND snooze_until < now()
`

func (q *Queries) GetExpiredSnoozeIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredSnoozeIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssue = `-- name: GetIssue :one
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues WHERE id = $1
`

func (q *Queries) GetIssue(ctx context.Context, id uuid.UUID) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
		&i.FirstRelease,
		&i.GithubIssueNumber,
		&i.GithubIssueUrl,
	)
	return i, err
}

const getIssueByFingerprint = `-- name: GetIssueByFingerprint :one
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues WHERE project_id = $1 AND fingerprint = $2
`

type GetIssueByFingerprintParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) GetIssueByFingerprint(ctx context.Context, arg GetIssueByFingerprintParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByFingerprint, arg.ProjectID, arg.Fingerprint)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
		&i.FirstRelease,
		&i.GithubIssueNumber,
		&i.GithubIssueUrl,
	)
	return i, err
}

const getIssueCountsByStatus = `-- name: GetIssueCountsByStatus :many
SELECT status, count(*)::int as count
FROM issues
WHERE project_id = $1
  AND ($2::text = '' OR level = $2::text
    OR ($2::text = 'errors' AND level IN ('error', 'fatal'))
    OR ($2::text = 'errors_w' AND level IN ('error', 'fatal', 'warning'))
    OR ($2::text = 'informational' AND level IN ('warning', 'info', 'debug'))
    OR ($2::text = 'info_only' AND level IN ('info', 'debug')))
GROUP BY status
`

type GetIssueCountsByStatusParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
}

type GetIssueCountsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) GetIssueCountsByStatus(ctx context.Context, arg GetIssueCountsByStatusParams) ([]GetIssueCountsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getIssueCountsByStatus, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIssueCountsByStatusRow{}
	for rows.Next() {
		var i GetIssueCountsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowingIssue = `-- name: IsFollowingIssue :one
SELECT EXISTS(SELECT 1 FROM issue_follows WHERE user_id = $1 AND issue_id = $2)::bool AS following
`

type IsFollowingIssueParams struct {
	UserID  uuid.UUID `json:"user_id"`
	IssueID uuid.UUID `json:"issue_id"`
}

func (q *Queries) IsFollowingIssue(ctx context.Context, arg IsFollowingIssueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowingIssue, arg.UserID, arg.IssueID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const listFollowedIssueIDs = `-- name: ListFollowedIssueIDs :many
SELECT issue_id FROM issue_follows WHERE user_id = $1
`

func (q *Queries) ListFollowedIssueIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listFollowedIssueIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var issue_id uuid.UUID
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueFollowers = `-- name: ListIssueFollowers :many
SELECT u.id, u.name, u.email FROM issue_follows f JOIN users u ON u.id = f.user_id WHERE f.issue_id = $1 ORDER BY f.created_at
`

type ListIssueFollowersRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) ListIssueFollowers(ctx context.Context, issueID uuid.UUID) ([]ListIssueFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueFollowers, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueFollowersRow{}
	for rows.Next() {
		var i ListIssueFollowersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueReleases = `-- name: ListIssueReleases :many
SELECT DISTINCT first_release FROM issues
WHERE project_id = $1 AND first_release != ''
ORDER BY first_release
`

func (q *Queries) ListIssueReleases(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIssueReleases, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var first_release string
		if err := rows.Scan(&first_release); err != nil {
			return nil, err
		}
		items = append(items, first_release)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByIDs = `-- name: ListIssuesByIDs :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues WHERE id = ANY($1::uuid[]) ORDER BY last_seen DESC
`

func (q *Queries) ListIssuesByIDs(ctx context.Context, ids []uuid.UUID) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByProject = `-- name: ListIssuesByProject :many

SELECT i.id, i.project_id, i.title, i.fingerprint, i.status, i.level, i.platform, i.first_seen, i.last_seen, i.event_count, i.assigned_to, i.resolved_at, i.cooldown_until, i.resolved_in_release, i.created_at, i.updated_at, i.snooze_until, i.snooze_event_threshold, i.snooze_events_at_start, i.jira_ticket_key, i.jira_ticket_url, i.priority, i.culprit, i.first_release, i.github_issue_number, i.github_issue_url, EXISTS(SELECT 1 FROM issue_follows f WHERE f.issue_id = i.id AND f.user_id = $7::uuid) AS followed
FROM issues i
WHERE i.project_id = $1
  AND ($2::text = '' OR i.status = $2::text)
  AND (NOT $5::bool OR i.first_seen >= CURRENT_DATE)
  AND (NOT $6::bool OR i.assigned_to IS NOT NULL)
  AND ($8::uuid IS NULL OR i.assigned_to = $8)
  AND ($9::text = '' OR i.level = $9::text
    OR ($9::text = 'errors' AND i.level IN ('error', 'fatal'))
    OR ($9::text = 'errors_w' AND i.level IN ('error', 'fatal', 'warning'))
    OR ($9::text = 'informational' AND i.level IN ('warning', 'info', 'debug'))
    OR ($9::text = 'info_only' AND i.level IN ('info', 'debug')))
  AND ($10::text = '' OR i.title ILIKE '%' || $10::text || '%')
  AND ($11::text = '' OR i.first_release = $11::text)
ORDER BY followed DESC, i.last_seen DESC
LIMIT $3 OFFSET $4
`

type ListIssuesByProjectParams struct {
	ProjectID      uuid.UUID     `json:"project_id"`
	Column2        string        `json:"column_2"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
	Column5        bool          `json:"column_5"`
	Column6        bool          `json:"column_6"`
	FollowerID     uuid.NullUUID `json:"follower_id"`
	AssignedToUser uuid.NullUUID `json:"assigned_to_user"`
	LevelFilter    string        `json:"level_filter"`
	Search         string        `json:"search"`
	ReleaseFilter  string        `json:"release_filter"`
}

type ListIssuesByProjectRow struct {
	ID                   uuid.UUID      `json:"id"`
	ProjectID            uuid.UUID      `json:"project_id"`
	Title                string         `json:"title"`
	Fingerprint          string         `json:"fingerprint"`
	Status               string         `json:"status"`
	Level                string         `json:"level"`
	Platform             string         `json:"platform"`
	FirstSeen            time.Time      `json:"first_seen"`
	LastSeen             time.Time      `json:"last_seen"`
	EventCount           int32          `json:"event_count"`
	AssignedTo           uuid.NullUUID  `json:"assigned_to"`
	ResolvedAt           sql.NullTime   `json:"resolved_at"`
	CooldownUntil        sql.NullTime   `json:"cooldown_until"`
	ResolvedInRelease    sql.NullString `json:"resolved_in_release"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	SnoozeUntil          sql.NullTime   `json:"snooze_until"`
	SnoozeEventThreshold sql.NullInt32  `json:"snooze_event_threshold"`
	SnoozeEventsAtStart  int32          `json:"snooze_events_at_start"`
	JiraTicketKey        sql.NullString `json:"jira_ticket_key"`
	JiraTicketUrl        sql.NullString `json:"jira_ticket_url"`
	Priority             int32          `json:"priority"`
	Culprit              string         `json:"culprit"`
	FirstRelease         string         `json:"first_release"`
	GithubIssueNumber    sql.NullInt32  `json:"github_issue_number"`
	GithubIssueUrl       sql.NullString `json:"github_issue_url"`
	Followed             bool           `json:"followed"`
}

// Level filter macro (repeated in each query):
//
//	'' = all, 'errors' = error+fatal, 'errors_w' = error+fatal+warning,
//	'informational' = warning+info+debug, 'info_only' = info+debug,
//	or exact level name
func (q *Queries) ListIssuesByProject(ctx context.Context, arg ListIssuesByProjectParams) ([]ListIssuesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.Column5,
		arg.Column6,
		arg.FollowerID,
		arg.AssignedToUser,
		arg.LevelFilter,
		arg.Search,
		arg.ReleaseFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByProjectRow{}
	for rows.Next() {
		var i ListIssuesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
			&i.Followed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesCreatedSince = `-- name: ListIssuesCreatedSince :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND first_seen >= $2
ORDER BY first_seen DESC
`

type ListIssuesCreatedSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FirstSeen time.Time `json:"first_seen"`
}

func (q *Queries) ListIssuesCreatedSince(ctx context.Context, arg ListIssuesCreatedSinceParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesCreatedSince, arg.ProjectID, arg.FirstSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesReopenedSince = `-- name: ListIssuesReopenedSince :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND status = 'reopened'
  AND last_seen >= $2
ORDER BY last_seen DESC
`

type ListIssuesReopenedSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	LastSeen  time.Time `json:"last_seen"`
}

func (q *Queries) ListIssuesReopenedSince(ctx context.Context, arg ListIssuesReopenedSinceParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesReopenedSince, arg.ProjectID, arg.LastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewIssuesSince = `-- name: ListNewIssuesSince :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND first_seen >= $2
  AND status IN ('open', 'reopened')
ORDER BY first_seen DESC
LIMIT 50
`

type ListNewIssuesSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FirstSeen time.Time `json:"first_seen"`
}

func (q *Queries) ListNewIssuesSince(ctx context.Context, arg ListNewIssuesSinceParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listNewIssuesSince, arg.ProjectID, arg.FirstSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenN1Issues = `-- name: ListOpenN1Issues :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND status = 'open'
  AND fingerprint LIKE 'n1:%'
`

func (q *Queries) ListOpenN1Issues(ctx context.Context, projectID uuid.UUID) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listOpenN1Issues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOpenIssues = `-- name: ListRecentOpenIssues :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND status IN ('open', 'reopened')
  AND id != $2
ORDER BY last_seen DESC
LIMIT 10
`

type ListRecentOpenIssuesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ListRecentOpenIssues(ctx context.Context, arg ListRecentOpenIssuesParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listRecentOpenIssues, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopIssuesByEvents = `-- name: ListTopIssuesByEvents :many
SELECT id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url FROM issues
WHERE project_id = $1
  AND status IN ('open', 'reopened')
ORDER BY event_count DESC
LIMIT $2
`

type ListTopIssuesByEventsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListTopIssuesByEvents(ctx context.Context, arg ListTopIssuesByEventsParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listTopIssuesByEvents, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Level,
			&i.Platform,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EventCount,
			&i.AssignedTo,
			&i.ResolvedAt,
			&i.CooldownUntil,
			&i.ResolvedInRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozeUntil,
			&i.SnoozeEventThreshold,
			&i.SnoozeEventsAtStart,
			&i.JiraTicketKey,
			&i.JiraTicketUrl,
			&i.Priority,
			&i.Culprit,
			&i.FirstRelease,
			&i.GithubIssueNumber,
			&i.GithubIssueUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowIssue = `-- name: UnfollowIssue :exec
DELETE FROM issue_follows WHERE user_id = $1 AND issue_id = $2
`

type UnfollowIssueParams struct {
	UserID  uuid.UUID `json:"user_id"`
	IssueID uuid.UUID `json:"issue_id"`
}

func (q *Queries) UnfollowIssue(ctx context.Context, arg UnfollowIssueParams) error {
	_, err := q.db.ExecContext(ctx, unfollowIssue, arg.UserID, arg.IssueID)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues
SET status = $2,
    resolved_at = $3,
    cooldown_until = $4,
    resolved_in_release = $5,
    snooze_until = $6,
    snooze_event_threshold = $7,
    snooze_events_at_start = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url
`

type UpdateIssueStatusParams struct {
	ID                   uuid.UUID      `json:"id"`
	Status               string         `json:"status"`
	ResolvedAt           sql.NullTime   `json:"resolved_at"`
	CooldownUntil        sql.NullTime   `json:"cooldown_until"`
	ResolvedInRelease    sql.NullString `json:"resolved_in_release"`
	SnoozeUntil          sql.NullTime   `json:"snooze_until"`
	SnoozeEventThreshold sql.NullInt32  `json:"snooze_event_threshold"`
	SnoozeEventsAtStart  int32          `json:"snooze_events_at_start"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssueStatus,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.CooldownUntil,
		arg.ResolvedInRelease,
		arg.SnoozeUntil,
		arg.SnoozeEventThreshold,
		arg.SnoozeEventsAtStart,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
		&i.FirstRelease,
		&i.GithubIssueNumber,
		&i.GithubIssueUrl,
	)
	return i, err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (project_id, title, fingerprint, level, platform, first_seen, last_seen, event_count, culprit, first_release)
VALUES ($1, $2, $3, $4, $5, $6, $6, 1, $7, $8)
ON CONFLICT (project_id, fingerprint) DO UPDATE
SET last_seen = $6,
    event_count = issues.event_count + 1,
    title = EXCLUDED.title,
    level = EXCLUDED.level,
    platform = EXCLUDED.platform,
    culprit = CASE WHEN EXCLUDED.culprit != '' THEN EXCLUDED.culprit ELSE issues.culprit END,
    updated_at = now()
RETURNING id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit, first_release, github_issue_number, github_issue_url
`

type UpsertIssueParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Title        string    `json:"title"`
	Fingerprint  string    `json:"fingerprint"`
	Level        string    `json:"level"`
	Platform     string    `json:"platform"`
	FirstSeen    time.Time `json:"first_seen"`
	Culprit      string    `json:"culprit"`
	FirstRelease string    `json:"first_release"`
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, upsertIssue,
		arg.ProjectID,
		arg.Title,
		arg.Fingerprint,
		arg.Level,
		arg.Platform,
		arg.FirstSeen,
		arg.Culprit,
		arg.FirstRelease,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
		&i.FirstRelease,
		&i.GithubIssueNumber,
		&i.GithubIssueUrl,
	)
	return i, err
}
