// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_aliases.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIssueAlias = `-- name: CreateIssueAlias :exec
INSERT INTO issue_aliases (project_id, fingerprint, primary_issue_id)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, fingerprint) DO UPDATE SET primary_issue_id = $3
`

type CreateIssueAliasParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	Fingerprint    string    `json:"fingerprint"`
	PrimaryIssueID uuid.UUID `json:"primary_issue_id"`
}

func (q *Queries) CreateIssueAlias(ctx context.Context, arg CreateIssueAliasParams) error {
	_, err := q.db.ExecContext(ctx, createIssueAlias, arg.ProjectID, arg.Fingerprint, arg.PrimaryIssueID)
	return err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const getIssueAlias = `-- name: GetIssueAlias :one
SELECT id, project_id, fingerprint, primary_issue_id, created_at FROM issue_aliases WHERE project_id = $1 AND fingerprint = $2
`

type GetIssueAliasParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) GetIssueAlias(ctx context.Context, arg GetIssueAliasParams) (IssueAlias, error) {
	row := q.db.QueryRowContext(ctx, getIssueAlias, arg.ProjectID, arg.Fingerprint)
	var i IssueAlias
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Fingerprint,
		&i.PrimaryIssueID,
		&i.CreatedAt,
	)
	return i, err
}

const moveEventsToIssue = `-- name: MoveEventsToIssue :execresult
UPDATE events SET issue_id = $2 WHERE issue_id = $1
`

type MoveEventsToIssueParams struct {
	IssueID   uuid.UUID `json:"issue_id"`
	IssueID_2 uuid.UUID `json:"issue_id_2"`
}

func (q *Queries) MoveEventsToIssue(ctx context.Context, arg MoveEventsToIssueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, moveEventsToIssue, arg.IssueID, arg.IssueID_2)
}

const recalcIssueStats = `-- name: RecalcIssueStats :one
UPDATE issues SET
    event_count = (SELECT count(*)::int FROM events e WHERE e.issue_id = issues.id),
    first_seen = COALESCE((SELECT min(e.timestamp) FROM events e WHERE e.issue_id = issues.id), issues.first_seen),
    last_seen = COALESCE((SELECT max(e.timestamp) FROM events e WHERE e.issue_id = issues.id), issues.last_seen),
    updated_at = now()
WHERE issues.id = $1
RETURNING id, project_id, title, fingerprint, status, level, platform, first_seen, last_seen, event_count, assigned_to, resolved_at, cooldown_until, resolved_in_release, created_at, updated_at, snooze_until, snooze_event_threshold, snooze_events_at_start, jira_ticket_key, jira_ticket_url, priority, culprit
`

func (q *Queries) RecalcIssueStats(ctx context.Context, id uuid.UUID) (Issue, error) {
	row := q.db.QueryRowContext(ctx, recalcIssueStats, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Level,
		&i.Platform,
		&i.FirstSeen,
		&i.LastSeen,
		&i.EventCount,
		&i.AssignedTo,
		&i.ResolvedAt,
		&i.CooldownUntil,
		&i.ResolvedInRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozeUntil,
		&i.SnoozeEventThreshold,
		&i.SnoozeEventsAtStart,
		&i.JiraTicketKey,
		&i.JiraTicketUrl,
		&i.Priority,
		&i.Culprit,
	)
	return i, err
}

const repointAliases = `-- name: RepointAliases :exec
UPDATE issue_aliases SET primary_issue_id = $2 WHERE primary_issue_id = $1
`

type RepointAliasesParams struct {
	PrimaryIssueID   uuid.UUID `json:"primary_issue_id"`
	PrimaryIssueID_2 uuid.UUID `json:"primary_issue_id_2"`
}

func (q *Queries) RepointAliases(ctx context.Context, arg RepointAliasesParams) error {
	_, err := q.db.ExecContext(ctx, repointAliases, arg.PrimaryIssueID, arg.PrimaryIssueID_2)
	return err
}
