// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countIssueComments = `-- name: CountIssueComments :one
SELECT count(*) FROM issue_comments WHERE issue_id = $1
`

func (q *Queries) CountIssueComments(ctx context.Context, issueID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssueComments, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssueComment = `-- name: CreateIssueComment :one
INSERT INTO issue_comments (issue_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, issue_id, user_id, body, created_at, updated_at
`

type CreateIssueCommentParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	UserID  uuid.UUID `json:"user_id"`
	Body    string    `json:"body"`
}

func (q *Queries) CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, createIssueComment, arg.IssueID, arg.UserID, arg.Body)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssueComment = `-- name: DeleteIssueComment :exec
DELETE FROM issue_comments WHERE id = $1
`

func (q *Queries) DeleteIssueComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIssueComment, id)
	return err
}

const getIssueComment = `-- name: GetIssueComment :one
SELECT id, issue_id, user_id, body, created_at, updated_at FROM issue_comments WHERE id = $1
`

func (q *Queries) GetIssueComment(ctx context.Context, id uuid.UUID) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, getIssueComment, id)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT c.id, c.issue_id, c.user_id, c.body, c.created_at, c.updated_at, u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar
FROM issue_comments c
JOIN users u ON u.id = c.user_id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC
`

type ListIssueCommentsRow struct {
	ID         uuid.UUID `json:"id"`
	IssueID    uuid.UUID `json:"issue_id"`
	UserID     uuid.UUID `json:"user_id"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	UserName   string    `json:"user_name"`
	UserEmail  string    `json:"user_email"`
	UserAvatar string    `json:"user_avatar"`
}

func (q *Queries) ListIssueComments(ctx context.Context, issueID uuid.UUID) ([]ListIssueCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueCommentsRow{}
	for rows.Next() {
		var i ListIssueCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueComment = `-- name: UpdateIssueComment :one
UPDATE issue_comments SET body = $2, updated_at = now()
WHERE id = $1
RETURNING id, issue_id, user_id, body, created_at, updated_at
`

type UpdateIssueCommentParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateIssueComment(ctx context.Context, arg UpdateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, updateIssueComment, arg.ID, arg.Body)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
