// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jira_rules.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createJiraRule = `-- name: CreateJiraRule :one
INSERT INTO jira_rules (project_id, name, enabled, level_filter, min_events, min_users, title_pattern, conditions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, created_at, updated_at, conditions
`

type CreateJiraRuleParams struct {
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) CreateJiraRule(ctx context.Context, arg CreateJiraRuleParams) (JiraRule, error) {
	row := q.db.QueryRowContext(ctx, createJiraRule,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.LevelFilter,
		arg.MinEvents,
		arg.MinUsers,
		arg.TitlePattern,
		arg.Conditions,
	)
	var i JiraRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}

const deleteJiraRule = `-- name: DeleteJiraRule :exec
DELETE FROM jira_rules WHERE id = $1 AND project_id = $2
`

type DeleteJiraRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteJiraRule(ctx context.Context, arg DeleteJiraRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteJiraRule, arg.ID, arg.ProjectID)
	return err
}

const getJiraRule = `-- name: GetJiraRule :one
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, created_at, updated_at, conditions FROM jira_rules WHERE id = $1
`

func (q *Queries) GetJiraRule(ctx context.Context, id uuid.UUID) (JiraRule, error) {
	row := q.db.QueryRowContext(ctx, getJiraRule, id)
	var i JiraRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}

const listEnabledJiraRules = `-- name: ListEnabledJiraRules :many
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, created_at, updated_at, conditions FROM jira_rules WHERE project_id = $1 AND enabled = true
`

func (q *Queries) ListEnabledJiraRules(ctx context.Context, projectID uuid.UUID) ([]JiraRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledJiraRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JiraRule{}
	for rows.Next() {
		var i JiraRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.LevelFilter,
			&i.MinEvents,
			&i.MinUsers,
			&i.TitlePattern,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJiraRules = `-- name: ListJiraRules :many
SELECT id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, created_at, updated_at, conditions FROM jira_rules WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListJiraRules(ctx context.Context, projectID uuid.UUID) ([]JiraRule, error) {
	rows, err := q.db.QueryContext(ctx, listJiraRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JiraRule{}
	for rows.Next() {
		var i JiraRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.LevelFilter,
			&i.MinEvents,
			&i.MinUsers,
			&i.TitlePattern,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueJiraTicket = `-- name: UpdateIssueJiraTicket :execresult
UPDATE issues SET jira_ticket_key = $2, jira_ticket_url = $3, updated_at = now()
WHERE id = $1 AND jira_ticket_key IS NULL
`

type UpdateIssueJiraTicketParams struct {
	ID            uuid.UUID      `json:"id"`
	JiraTicketKey sql.NullString `json:"jira_ticket_key"`
	JiraTicketUrl sql.NullString `json:"jira_ticket_url"`
}

func (q *Queries) UpdateIssueJiraTicket(ctx context.Context, arg UpdateIssueJiraTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateIssueJiraTicket, arg.ID, arg.JiraTicketKey, arg.JiraTicketUrl)
}

const updateJiraRule = `-- name: UpdateJiraRule :one
UPDATE jira_rules
SET name = $3, enabled = $4, level_filter = $5, min_events = $6, min_users = $7, title_pattern = $8, conditions = $9, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, enabled, level_filter, min_events, min_users, title_pattern, created_at, updated_at, conditions
`

type UpdateJiraRuleParams struct {
	ID           uuid.UUID             `json:"id"`
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) UpdateJiraRule(ctx context.Context, arg UpdateJiraRuleParams) (JiraRule, error) {
	row := q.db.QueryRowContext(ctx, updateJiraRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.LevelFilter,
		arg.MinEvents,
		arg.MinUsers,
		arg.TitlePattern,
		arg.Conditions,
	)
	var i JiraRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.LevelFilter,
		&i.MinEvents,
		&i.MinUsers,
		&i.TitlePattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}
