// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AlertConfig struct {
	ID             uuid.UUID             `json:"id"`
	ProjectID      uuid.UUID             `json:"project_id"`
	AlertType      string                `json:"alert_type"`
	Config         json.RawMessage       `json:"config"`
	Enabled        bool                  `json:"enabled"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
	LevelFilter    string                `json:"level_filter"`
	TitlePattern   string                `json:"title_pattern"`
	MinEvents      int32                 `json:"min_events"`
	MinVelocity1h  int32                 `json:"min_velocity_1h"`
	ExcludePattern string                `json:"exclude_pattern"`
	Conditions     pqtype.NullRawMessage `json:"conditions"`
}

type ApiToken struct {
	ID         uuid.UUID     `json:"id"`
	ProjectID  uuid.NullUUID `json:"project_id"`
	TokenHash  string        `json:"token_hash"`
	Name       string        `json:"name"`
	Permission string        `json:"permission"`
	LastUsedAt sql.NullTime  `json:"last_used_at"`
	ExpiresAt  sql.NullTime  `json:"expires_at"`
	CreatedBy  uuid.NullUUID `json:"created_by"`
	CreatedAt  time.Time     `json:"created_at"`
	Scope      string        `json:"scope"`
}

type Deploy struct {
	ID             uuid.UUID      `json:"id"`
	ProjectID      uuid.UUID      `json:"project_id"`
	ReleaseVersion string         `json:"release_version"`
	CommitSha      sql.NullString `json:"commit_sha"`
	Environment    string         `json:"environment"`
	Url            sql.NullString `json:"url"`
	DeployedAt     time.Time      `json:"deployed_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Event struct {
	ID             uuid.UUID       `json:"id"`
	IssueID        uuid.UUID       `json:"issue_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	EventID        string          `json:"event_id"`
	Timestamp      time.Time       `json:"timestamp"`
	Platform       string          `json:"platform"`
	Level          string          `json:"level"`
	Message        string          `json:"message"`
	Release        string          `json:"release"`
	Environment    string          `json:"environment"`
	ServerName     string          `json:"server_name"`
	Data           json.RawMessage `json:"data"`
	CreatedAt      time.Time       `json:"created_at"`
	UserIdentifier string          `json:"user_identifier"`
}

type GithubRule struct {
	ID           uuid.UUID             `json:"id"`
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type Issue struct {
	ID                   uuid.UUID      `json:"id"`
	ProjectID            uuid.UUID      `json:"project_id"`
	Title                string         `json:"title"`
	Fingerprint          string         `json:"fingerprint"`
	Status               string         `json:"status"`
	Level                string         `json:"level"`
	Platform             string         `json:"platform"`
	FirstSeen            time.Time      `json:"first_seen"`
	LastSeen             time.Time      `json:"last_seen"`
	EventCount           int32          `json:"event_count"`
	AssignedTo           uuid.NullUUID  `json:"assigned_to"`
	ResolvedAt           sql.NullTime   `json:"resolved_at"`
	CooldownUntil        sql.NullTime   `json:"cooldown_until"`
	ResolvedInRelease    sql.NullString `json:"resolved_in_release"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	SnoozeUntil          sql.NullTime   `json:"snooze_until"`
	SnoozeEventThreshold sql.NullInt32  `json:"snooze_event_threshold"`
	SnoozeEventsAtStart  int32          `json:"snooze_events_at_start"`
	JiraTicketKey        sql.NullString `json:"jira_ticket_key"`
	JiraTicketUrl        sql.NullString `json:"jira_ticket_url"`
	Priority             int32          `json:"priority"`
	Culprit              string         `json:"culprit"`
	FirstRelease         string         `json:"first_release"`
	GithubIssueNumber    sql.NullInt32  `json:"github_issue_number"`
	GithubIssueUrl       sql.NullString `json:"github_issue_url"`
}

type IssueActivity struct {
	ID        uuid.UUID             `json:"id"`
	IssueID   uuid.UUID             `json:"issue_id"`
	TicketID  uuid.NullUUID         `json:"ticket_id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Action    string                `json:"action"`
	OldValue  sql.NullString        `json:"old_value"`
	NewValue  sql.NullString        `json:"new_value"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

type IssueAlias struct {
	ID             uuid.UUID `json:"id"`
	ProjectID      uuid.UUID `json:"project_id"`
	Fingerprint    string    `json:"fingerprint"`
	PrimaryIssueID uuid.UUID `json:"primary_issue_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type IssueComment struct {
	ID        uuid.UUID `json:"id"`
	IssueID   uuid.UUID `json:"issue_id"`
	UserID    uuid.UUID `json:"user_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type IssueFollow struct {
	UserID    uuid.UUID `json:"user_id"`
	IssueID   uuid.UUID `json:"issue_id"`
	CreatedAt time.Time `json:"created_at"`
}

type IssueTag struct {
	ID        uuid.UUID `json:"id"`
	IssueID   uuid.UUID `json:"issue_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type JiraRule struct {
	ID           uuid.UUID             `json:"id"`
	ProjectID    uuid.UUID             `json:"project_id"`
	Name         string                `json:"name"`
	Enabled      bool                  `json:"enabled"`
	LevelFilter  string                `json:"level_filter"`
	MinEvents    int32                 `json:"min_events"`
	MinUsers     int32                 `json:"min_users"`
	TitlePattern string                `json:"title_pattern"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	Conditions   pqtype.NullRawMessage `json:"conditions"`
}

type PriorityRule struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	RuleType   string                `json:"rule_type"`
	Pattern    string                `json:"pattern"`
	Operator   string                `json:"operator"`
	Threshold  int32                 `json:"threshold"`
	Points     int32                 `json:"points"`
	Enabled    bool                  `json:"enabled"`
	Position   int32                 `json:"position"`
	CreatedAt  time.Time             `json:"created_at"`
	UpdatedAt  time.Time             `json:"updated_at"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

type Project struct {
	ID                     uuid.UUID     `json:"id"`
	Name                   string        `json:"name"`
	Slug                   string        `json:"slug"`
	DefaultCooldownMinutes int32         `json:"default_cooldown_minutes"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at"`
	WarningAsError         bool          `json:"warning_as_error"`
	JiraBaseUrl            string        `json:"jira_base_url"`
	JiraEmail              string        `json:"jira_email"`
	JiraApiToken           string        `json:"jira_api_token"`
	JiraProjectKey         string        `json:"jira_project_key"`
	JiraIssueType          string        `json:"jira_issue_type"`
	GroupID                uuid.NullUUID `json:"group_id"`
	MaxEventsPerIssue      int32         `json:"max_events_per_issue"`
	Icon                   string        `json:"icon"`
	Color                  string        `json:"color"`
	Position               int32         `json:"position"`
	NumericID              int32         `json:"numeric_id"`
	IssueDisplayMode       string        `json:"issue_display_mode"`
	GithubToken            string        `json:"github_token"`
	GithubOwner            string        `json:"github_owner"`
	GithubRepo             string        `json:"github_repo"`
	GithubLabels           string        `json:"github_labels"`
	WorkflowMode           string        `json:"workflow_mode"`
	RepoProvider           string        `json:"repo_provider"`
	RepoOwner              string        `json:"repo_owner"`
	RepoName               string        `json:"repo_name"`
	RepoDefaultBranch      string        `json:"repo_default_branch"`
	RepoToken              string        `json:"repo_token"`
	RepoPathStrip          string        `json:"repo_path_strip"`
}

type ProjectFavorite struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectGroup struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectKey struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	PublicKey string    `json:"public_key"`
	SecretKey string    `json:"secret_key"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type QueryPattern struct {
	ID              uuid.UUID `json:"id"`
	ProjectID       uuid.UUID `json:"project_id"`
	Transaction     string    `json:"transaction"`
	QueryHash       string    `json:"query_hash"`
	NormalizedQuery string    `json:"normalized_query"`
	TableName       string    `json:"table_name"`
	EventCount      int32     `json:"event_count"`
	DistinctEvents  int32     `json:"distinct_events"`
	TotalExecMs     float64   `json:"total_exec_ms"`
	FirstSeen       time.Time `json:"first_seen"`
	LastSeen        time.Time `json:"last_seen"`
}

type ReleaseCommit struct {
	ID             uuid.UUID      `json:"id"`
	ProjectID      uuid.UUID      `json:"project_id"`
	ReleaseVersion string         `json:"release_version"`
	CommitSha      string         `json:"commit_sha"`
	CommitUrl      sql.NullString `json:"commit_url"`
	CommittedAt    sql.NullTime   `json:"committed_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TagRule struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	Pattern    string                `json:"pattern"`
	TagKey     string                `json:"tag_key"`
	TagValue   string                `json:"tag_value"`
	Enabled    bool                  `json:"enabled"`
	CreatedAt  time.Time             `json:"created_at"`
	UpdatedAt  time.Time             `json:"updated_at"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

type Ticket struct {
	ID              uuid.UUID      `json:"id"`
	IssueID         uuid.NullUUID  `json:"issue_id"`
	ProjectID       uuid.UUID      `json:"project_id"`
	Status          string         `json:"status"`
	AssignedTo      uuid.NullUUID  `json:"assigned_to"`
	CreatedBy       uuid.UUID      `json:"created_by"`
	Priority        int32          `json:"priority"`
	DueDate         sql.NullTime   `json:"due_date"`
	ResolutionType  sql.NullString `json:"resolution_type"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	FixReference    sql.NullString `json:"fix_reference"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	EscalatedSystem sql.NullString `json:"escalated_system"`
	EscalatedKey    sql.NullString `json:"escalated_key"`
	EscalatedUrl    sql.NullString `json:"escalated_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Role      string         `json:"role"`
	GoogleID  sql.NullString `json:"google_id"`
	AvatarUrl string         `json:"avatar_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Status    string         `json:"status"`
}
