// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: priority_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPriorityRule = `-- name: CreatePriorityRule :one
INSERT INTO priority_rules (project_id, name, rule_type, pattern, operator, threshold, points, enabled, position, conditions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE((SELECT max(position) + 1 FROM priority_rules WHERE project_id = $1), 0), $9)
RETURNING id, project_id, name, rule_type, pattern, operator, threshold, points, enabled, position, created_at, updated_at, conditions
`

type CreatePriorityRuleParams struct {
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	RuleType   string                `json:"rule_type"`
	Pattern    string                `json:"pattern"`
	Operator   string                `json:"operator"`
	Threshold  int32                 `json:"threshold"`
	Points     int32                 `json:"points"`
	Enabled    bool                  `json:"enabled"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) CreatePriorityRule(ctx context.Context, arg CreatePriorityRuleParams) (PriorityRule, error) {
	row := q.db.QueryRowContext(ctx, createPriorityRule,
		arg.ProjectID,
		arg.Name,
		arg.RuleType,
		arg.Pattern,
		arg.Operator,
		arg.Threshold,
		arg.Points,
		arg.Enabled,
		arg.Conditions,
	)
	var i PriorityRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RuleType,
		&i.Pattern,
		&i.Operator,
		&i.Threshold,
		&i.Points,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}

const deletePriorityRule = `-- name: DeletePriorityRule :exec
DELETE FROM priority_rules WHERE id = $1 AND project_id = $2
`

type DeletePriorityRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePriorityRule(ctx context.Context, arg DeletePriorityRuleParams) error {
	_, err := q.db.ExecContext(ctx, deletePriorityRule, arg.ID, arg.ProjectID)
	return err
}

const getIssueVelocity1h = `-- name: GetIssueVelocity1h :one
SELECT COUNT(*)::int as count FROM events
WHERE issue_id = $1 AND timestamp >= now() - interval '1 hour'
`

func (q *Queries) GetIssueVelocity1h(ctx context.Context, issueID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getIssueVelocity1h, issueID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getIssueVelocity24h = `-- name: GetIssueVelocity24h :one
SELECT COUNT(*)::int as count FROM events
WHERE issue_id = $1 AND timestamp >= now() - interval '24 hours'
`

func (q *Queries) GetIssueVelocity24h(ctx context.Context, issueID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getIssueVelocity24h, issueID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listEnabledPriorityRules = `-- name: ListEnabledPriorityRules :many
SELECT id, project_id, name, rule_type, pattern, operator, threshold, points, enabled, position, created_at, updated_at, conditions FROM priority_rules WHERE project_id = $1 AND enabled = true ORDER BY position
`

func (q *Queries) ListEnabledPriorityRules(ctx context.Context, projectID uuid.UUID) ([]PriorityRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPriorityRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriorityRule{}
	for rows.Next() {
		var i PriorityRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RuleType,
			&i.Pattern,
			&i.Operator,
			&i.Threshold,
			&i.Points,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueIDsByProject = `-- name: ListIssueIDsByProject :many
SELECT id FROM issues WHERE project_id = $1
`

func (q *Queries) ListIssueIDsByProject(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listIssueIDsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriorityRules = `-- name: ListPriorityRules :many
SELECT id, project_id, name, rule_type, pattern, operator, threshold, points, enabled, position, created_at, updated_at, conditions FROM priority_rules WHERE project_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListPriorityRules(ctx context.Context, projectID uuid.UUID) ([]PriorityRule, error) {
	rows, err := q.db.QueryContext(ctx, listPriorityRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriorityRule{}
	for rows.Next() {
		var i PriorityRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RuleType,
			&i.Pattern,
			&i.Operator,
			&i.Threshold,
			&i.Points,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssuePriority = `-- name: UpdateIssuePriority :exec
UPDATE issues SET priority = $2, updated_at = now() WHERE id = $1
`

type UpdateIssuePriorityParams struct {
	ID       uuid.UUID `json:"id"`
	Priority int32     `json:"priority"`
}

func (q *Queries) UpdateIssuePriority(ctx context.Context, arg UpdateIssuePriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateIssuePriority, arg.ID, arg.Priority)
	return err
}

const updatePriorityRule = `-- name: UpdatePriorityRule :one
UPDATE priority_rules
SET name = $3, rule_type = $4, pattern = $5, operator = $6, threshold = $7, points = $8, enabled = $9, conditions = $10, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, rule_type, pattern, operator, threshold, points, enabled, position, created_at, updated_at, conditions
`

type UpdatePriorityRuleParams struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	RuleType   string                `json:"rule_type"`
	Pattern    string                `json:"pattern"`
	Operator   string                `json:"operator"`
	Threshold  int32                 `json:"threshold"`
	Points     int32                 `json:"points"`
	Enabled    bool                  `json:"enabled"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) UpdatePriorityRule(ctx context.Context, arg UpdatePriorityRuleParams) (PriorityRule, error) {
	row := q.db.QueryRowContext(ctx, updatePriorityRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.RuleType,
		arg.Pattern,
		arg.Operator,
		arg.Threshold,
		arg.Points,
		arg.Enabled,
		arg.Conditions,
	)
	var i PriorityRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RuleType,
		&i.Pattern,
		&i.Operator,
		&i.Threshold,
		&i.Points,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}
