// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProjectGroup = `-- name: CreateProjectGroup :one
INSERT INTO project_groups (name, position)
VALUES ($1, COALESCE((SELECT max(position) + 1 FROM project_groups), 0))
RETURNING id, name, position, created_at
`

func (q *Queries) CreateProjectGroup(ctx context.Context, name string) (ProjectGroup, error) {
	row := q.db.QueryRowContext(ctx, createProjectGroup, name)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectGroup = `-- name: DeleteProjectGroup :exec
DELETE FROM project_groups WHERE id = $1
`

func (q *Queries) DeleteProjectGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectGroup, id)
	return err
}

const listProjectGroups = `-- name: ListProjectGroups :many
SELECT id, name, position, created_at FROM project_groups ORDER BY position, name
`

func (q *Queries) ListProjectGroups(ctx context.Context) ([]ProjectGroup, error) {
	rows, err := q.db.QueryContext(ctx, listProjectGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectGroup{}
	for rows.Next() {
		var i ProjectGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectGroup = `-- name: SetProjectGroup :exec
UPDATE projects SET group_id = $2, updated_at = now() WHERE id = $1
`

type SetProjectGroupParams struct {
	ID      uuid.UUID     `json:"id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

func (q *Queries) SetProjectGroup(ctx context.Context, arg SetProjectGroupParams) error {
	_, err := q.db.ExecContext(ctx, setProjectGroup, arg.ID, arg.GroupID)
	return err
}

const updateProjectGroup = `-- name: UpdateProjectGroup :one
UPDATE project_groups SET name = $2 WHERE id = $1 RETURNING id, name, position, created_at
`

type UpdateProjectGroupParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateProjectGroup(ctx context.Context, arg UpdateProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRowContext(ctx, updateProjectGroup, arg.ID, arg.Name)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
