// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, default_cooldown_minutes)
VALUES ($1, $2, $3)
RETURNING id, name, slug, default_cooldown_minutes, created_at, updated_at, warning_as_error, jira_base_url, jira_email, jira_api_token, jira_project_key, jira_issue_type, group_id, max_events_per_issue, icon, color, position
`

type CreateProjectParams struct {
	Name                   string `json:"name"`
	Slug                   string `json:"slug"`
	DefaultCooldownMinutes int32  `json:"default_cooldown_minutes"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Slug, arg.DefaultCooldownMinutes)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultCooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarningAsError,
		&i.JiraBaseUrl,
		&i.JiraEmail,
		&i.JiraApiToken,
		&i.JiraProjectKey,
		&i.JiraIssueType,
		&i.GroupID,
		&i.MaxEventsPerIssue,
		&i.Icon,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const createProjectKey = `-- name: CreateProjectKey :one
INSERT INTO project_keys (project_id, public_key, secret_key, label)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, public_key, secret_key, label, created_at
`

type CreateProjectKeyParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	PublicKey string    `json:"public_key"`
	SecretKey string    `json:"secret_key"`
	Label     string    `json:"label"`
}

func (q *Queries) CreateProjectKey(ctx context.Context, arg CreateProjectKeyParams) (ProjectKey, error) {
	row := q.db.QueryRowContext(ctx, createProjectKey,
		arg.ProjectID,
		arg.PublicKey,
		arg.SecretKey,
		arg.Label,
	)
	var i ProjectKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PublicKey,
		&i.SecretKey,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, slug, default_cooldown_minutes, created_at, updated_at, warning_as_error, jira_base_url, jira_email, jira_api_token, jira_project_key, jira_issue_type, group_id, max_events_per_issue, icon, color, position FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultCooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarningAsError,
		&i.JiraBaseUrl,
		&i.JiraEmail,
		&i.JiraApiToken,
		&i.JiraProjectKey,
		&i.JiraIssueType,
		&i.GroupID,
		&i.MaxEventsPerIssue,
		&i.Icon,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, default_cooldown_minutes, created_at, updated_at, warning_as_error, jira_base_url, jira_email, jira_api_token, jira_project_key, jira_issue_type, group_id, max_events_per_issue, icon, color, position FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultCooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarningAsError,
		&i.JiraBaseUrl,
		&i.JiraEmail,
		&i.JiraApiToken,
		&i.JiraProjectKey,
		&i.JiraIssueType,
		&i.GroupID,
		&i.MaxEventsPerIssue,
		&i.Icon,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const getProjectEventTrend = `-- name: GetProjectEventTrend :many
SELECT project_id,
       date_trunc('day', timestamp)::timestamptz as bucket,
       COUNT(*)::int as count
FROM events
WHERE timestamp >= now() - interval '14 days'
  AND level IN ('error', 'fatal')
GROUP BY project_id, bucket
ORDER BY project_id, bucket
`

type GetProjectEventTrendRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	Bucket    time.Time `json:"bucket"`
	Count     int32     `json:"count"`
}

func (q *Queries) GetProjectEventTrend(ctx context.Context) ([]GetProjectEventTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectEventTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEventTrendRow{}
	for rows.Next() {
		var i GetProjectEventTrendRow
		if err := rows.Scan(&i.ProjectID, &i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectKeyByPublic = `-- name: GetProjectKeyByPublic :one
SELECT id, project_id, public_key, secret_key, label, created_at FROM project_keys WHERE public_key = $1
`

func (q *Queries) GetProjectKeyByPublic(ctx context.Context, publicKey string) (ProjectKey, error) {
	row := q.db.QueryRowContext(ctx, getProjectKeyByPublic, publicKey)
	var i ProjectKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PublicKey,
		&i.SecretKey,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectLatestRelease = `-- name: GetProjectLatestRelease :many
SELECT DISTINCT ON (project_id) project_id, release
FROM events
WHERE release != ''
  AND level IN ('error', 'fatal')
ORDER BY project_id, timestamp DESC
`

type GetProjectLatestReleaseRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	Release   string    `json:"release"`
}

func (q *Queries) GetProjectLatestRelease(ctx context.Context) ([]GetProjectLatestReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectLatestRelease)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectLatestReleaseRow{}
	for rows.Next() {
		var i GetProjectLatestReleaseRow
		if err := rows.Scan(&i.ProjectID, &i.Release); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectStats = `-- name: GetProjectStats :many
SELECT
  project_id,
  count(*)::int AS total_issues,
  count(*) FILTER (WHERE status IN ('open', 'reopened') AND level IN ('error', 'fatal'))::int AS open_issues,
  max(last_seen) AS latest_event
FROM issues
GROUP BY project_id
`

type GetProjectStatsRow struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	TotalIssues int32       `json:"total_issues"`
	OpenIssues  int32       `json:"open_issues"`
	LatestEvent interface{} `json:"latest_event"`
}

func (q *Queries) GetProjectStats(ctx context.Context) ([]GetProjectStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectStatsRow{}
	for rows.Next() {
		var i GetProjectStatsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.TotalIssues,
			&i.OpenIssues,
			&i.LatestEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectWeeklyErrors = `-- name: GetProjectWeeklyErrors :many
SELECT project_id,
       COUNT(*) FILTER (WHERE timestamp >= now() - interval '7 days')::int as this_week,
       COUNT(*) FILTER (WHERE timestamp >= now() - interval '14 days' AND timestamp < now() - interval '7 days')::int as last_week
FROM events
WHERE timestamp >= now() - interval '14 days'
  AND level IN ('error', 'fatal')
GROUP BY project_id
`

type GetProjectWeeklyErrorsRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	ThisWeek  int32     `json:"this_week"`
	LastWeek  int32     `json:"last_week"`
}

func (q *Queries) GetProjectWeeklyErrors(ctx context.Context) ([]GetProjectWeeklyErrorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectWeeklyErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectWeeklyErrorsRow{}
	for rows.Next() {
		var i GetProjectWeeklyErrorsRow
		if err := rows.Scan(&i.ProjectID, &i.ThisWeek, &i.LastWeek); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectKeys = `-- name: ListProjectKeys :many
SELECT id, project_id, public_key, secret_key, label, created_at FROM project_keys WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListProjectKeys(ctx context.Context, projectID uuid.UUID) ([]ProjectKey, error) {
	rows, err := q.db.QueryContext(ctx, listProjectKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectKey{}
	for rows.Next() {
		var i ProjectKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PublicKey,
			&i.SecretKey,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, default_cooldown_minutes, created_at, updated_at, warning_as_error, jira_base_url, jira_email, jira_api_token, jira_project_key, jira_issue_type, group_id, max_events_per_issue, icon, color, position FROM projects ORDER BY position, created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DefaultCooldownMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WarningAsError,
			&i.JiraBaseUrl,
			&i.JiraEmail,
			&i.JiraApiToken,
			&i.JiraProjectKey,
			&i.JiraIssueType,
			&i.GroupID,
			&i.MaxEventsPerIssue,
			&i.Icon,
			&i.Color,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, slug = $3, default_cooldown_minutes = $4, warning_as_error = $5,
    jira_base_url = $6, jira_email = $7, jira_api_token = $8, jira_project_key = $9, jira_issue_type = $10,
    max_events_per_issue = $11,
    icon = $12, color = $13,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, default_cooldown_minutes, created_at, updated_at, warning_as_error, jira_base_url, jira_email, jira_api_token, jira_project_key, jira_issue_type, group_id, max_events_per_issue, icon, color, position
`

type UpdateProjectParams struct {
	ID                     uuid.UUID `json:"id"`
	Name                   string    `json:"name"`
	Slug                   string    `json:"slug"`
	DefaultCooldownMinutes int32     `json:"default_cooldown_minutes"`
	WarningAsError         bool      `json:"warning_as_error"`
	JiraBaseUrl            string    `json:"jira_base_url"`
	JiraEmail              string    `json:"jira_email"`
	JiraApiToken           string    `json:"jira_api_token"`
	JiraProjectKey         string    `json:"jira_project_key"`
	JiraIssueType          string    `json:"jira_issue_type"`
	MaxEventsPerIssue      int32     `json:"max_events_per_issue"`
	Icon                   string    `json:"icon"`
	Color                  string    `json:"color"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DefaultCooldownMinutes,
		arg.WarningAsError,
		arg.JiraBaseUrl,
		arg.JiraEmail,
		arg.JiraApiToken,
		arg.JiraProjectKey,
		arg.JiraIssueType,
		arg.MaxEventsPerIssue,
		arg.Icon,
		arg.Color,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultCooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarningAsError,
		&i.JiraBaseUrl,
		&i.JiraEmail,
		&i.JiraApiToken,
		&i.JiraProjectKey,
		&i.JiraIssueType,
		&i.GroupID,
		&i.MaxEventsPerIssue,
		&i.Icon,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const updateProjectPosition = `-- name: UpdateProjectPosition :exec
UPDATE projects SET position = $2 WHERE id = $1
`

type UpdateProjectPositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateProjectPosition(ctx context.Context, arg UpdateProjectPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectPosition, arg.ID, arg.Position)
	return err
}
