// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_patterns.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupOldQueryPatterns = `-- name: CleanupOldQueryPatterns :exec
DELETE FROM query_patterns WHERE last_seen < now() - interval '30 days'
`

func (q *Queries) CleanupOldQueryPatterns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOldQueryPatterns)
	return err
}

const listN1Candidates = `-- name: ListN1Candidates :many
SELECT id, project_id, transaction, query_hash, normalized_query, table_name, event_count, distinct_events, total_exec_ms, first_seen, last_seen,
       (event_count::float / GREATEST(distinct_events, 1)) AS avg_per_event
FROM query_patterns
WHERE project_id = $1
  AND distinct_events >= $2
  AND (event_count::float / GREATEST(distinct_events, 1)) >= $3
ORDER BY (event_count::float / GREATEST(distinct_events, 1)) * distinct_events DESC
`

type ListN1CandidatesParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	DistinctEvents int32     `json:"distinct_events"`
	EventCount     int32     `json:"event_count"`
}

type ListN1CandidatesRow struct {
	ID              uuid.UUID `json:"id"`
	ProjectID       uuid.UUID `json:"project_id"`
	Transaction     string    `json:"transaction"`
	QueryHash       string    `json:"query_hash"`
	NormalizedQuery string    `json:"normalized_query"`
	TableName       string    `json:"table_name"`
	EventCount      int32     `json:"event_count"`
	DistinctEvents  int32     `json:"distinct_events"`
	TotalExecMs     float64   `json:"total_exec_ms"`
	FirstSeen       time.Time `json:"first_seen"`
	LastSeen        time.Time `json:"last_seen"`
	AvgPerEvent     int32     `json:"avg_per_event"`
}

func (q *Queries) ListN1Candidates(ctx context.Context, arg ListN1CandidatesParams) ([]ListN1CandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listN1Candidates, arg.ProjectID, arg.DistinctEvents, arg.EventCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListN1CandidatesRow{}
	for rows.Next() {
		var i ListN1CandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Transaction,
			&i.QueryHash,
			&i.NormalizedQuery,
			&i.TableName,
			&i.EventCount,
			&i.DistinctEvents,
			&i.TotalExecMs,
			&i.FirstSeen,
			&i.LastSeen,
			&i.AvgPerEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryPatterns = `-- name: ListQueryPatterns :many
SELECT id, project_id, transaction, query_hash, normalized_query, table_name, event_count, distinct_events, total_exec_ms, first_seen, last_seen FROM query_patterns
WHERE project_id = $1
ORDER BY event_count DESC
LIMIT $2
`

type ListQueryPatternsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListQueryPatterns(ctx context.Context, arg ListQueryPatternsParams) ([]QueryPattern, error) {
	rows, err := q.db.QueryContext(ctx, listQueryPatterns, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryPattern{}
	for rows.Next() {
		var i QueryPattern
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Transaction,
			&i.QueryHash,
			&i.NormalizedQuery,
			&i.TableName,
			&i.EventCount,
			&i.DistinctEvents,
			&i.TotalExecMs,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQueryPattern = `-- name: UpsertQueryPattern :exec
INSERT INTO query_patterns (project_id, transaction, query_hash, normalized_query, table_name, event_count, distinct_events, total_exec_ms, first_seen, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7, now(), now())
ON CONFLICT (project_id, transaction, query_hash) DO UPDATE
SET event_count = query_patterns.event_count + EXCLUDED.event_count,
    distinct_events = query_patterns.distinct_events + 1,
    total_exec_ms = query_patterns.total_exec_ms + EXCLUDED.total_exec_ms,
    last_seen = now()
`

type UpsertQueryPatternParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	Transaction     string    `json:"transaction"`
	QueryHash       string    `json:"query_hash"`
	NormalizedQuery string    `json:"normalized_query"`
	TableName       string    `json:"table_name"`
	EventCount      int32     `json:"event_count"`
	TotalExecMs     float64   `json:"total_exec_ms"`
}

func (q *Queries) UpsertQueryPattern(ctx context.Context, arg UpsertQueryPatternParams) error {
	_, err := q.db.ExecContext(ctx, upsertQueryPattern,
		arg.ProjectID,
		arg.Transaction,
		arg.QueryHash,
		arg.NormalizedQuery,
		arg.TableName,
		arg.EventCount,
		arg.TotalExecMs,
	)
	return err
}
