// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDeploy = `-- name: CreateDeploy :one
INSERT INTO deploys (project_id, release_version, commit_sha, environment, url, deployed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, release_version, commit_sha, environment, url, deployed_at, created_at
`

type CreateDeployParams struct {
	ProjectID      uuid.UUID      `json:"project_id"`
	ReleaseVersion string         `json:"release_version"`
	CommitSha      sql.NullString `json:"commit_sha"`
	Environment    string         `json:"environment"`
	Url            sql.NullString `json:"url"`
	DeployedAt     time.Time      `json:"deployed_at"`
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, createDeploy,
		arg.ProjectID,
		arg.ReleaseVersion,
		arg.CommitSha,
		arg.Environment,
		arg.Url,
		arg.DeployedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseVersion,
		&i.CommitSha,
		&i.Environment,
		&i.Url,
		&i.DeployedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDeployForRelease = `-- name: GetLatestDeployForRelease :one
SELECT id, project_id, release_version, commit_sha, environment, url, deployed_at, created_at FROM deploys WHERE project_id = $1 AND release_version = $2 ORDER BY deployed_at DESC LIMIT 1
`

type GetLatestDeployForReleaseParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	ReleaseVersion string    `json:"release_version"`
}

func (q *Queries) GetLatestDeployForRelease(ctx context.Context, arg GetLatestDeployForReleaseParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeployForRelease, arg.ProjectID, arg.ReleaseVersion)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseVersion,
		&i.CommitSha,
		&i.Environment,
		&i.Url,
		&i.DeployedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviousRelease = `-- name: GetPreviousRelease :one
SELECT id, project_id, release_version, commit_sha, commit_url, committed_at, created_at FROM release_commits rc
WHERE rc.project_id = $1 AND rc.created_at < (SELECT rc2.created_at FROM release_commits rc2 WHERE rc2.project_id = $1 AND rc2.release_version = $2)
ORDER BY rc.created_at DESC LIMIT 1
`

type GetPreviousReleaseParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	ReleaseVersion string    `json:"release_version"`
}

func (q *Queries) GetPreviousRelease(ctx context.Context, arg GetPreviousReleaseParams) (ReleaseCommit, error) {
	row := q.db.QueryRowContext(ctx, getPreviousRelease, arg.ProjectID, arg.ReleaseVersion)
	var i ReleaseCommit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseVersion,
		&i.CommitSha,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseCommit = `-- name: GetReleaseCommit :one
SELECT id, project_id, release_version, commit_sha, commit_url, committed_at, created_at FROM release_commits WHERE project_id = $1 AND release_version = $2
`

type GetReleaseCommitParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	ReleaseVersion string    `json:"release_version"`
}

func (q *Queries) GetReleaseCommit(ctx context.Context, arg GetReleaseCommitParams) (ReleaseCommit, error) {
	row := q.db.QueryRowContext(ctx, getReleaseCommit, arg.ProjectID, arg.ReleaseVersion)
	var i ReleaseCommit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseVersion,
		&i.CommitSha,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploys = `-- name: ListDeploys :many
SELECT id, project_id, release_version, commit_sha, environment, url, deployed_at, created_at FROM deploys WHERE project_id = $1 ORDER BY deployed_at DESC LIMIT $2
`

type ListDeploysParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListDeploys(ctx context.Context, arg ListDeploysParams) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploys, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleaseVersion,
			&i.CommitSha,
			&i.Environment,
			&i.Url,
			&i.DeployedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseCommits = `-- name: ListReleaseCommits :many
SELECT id, project_id, release_version, commit_sha, commit_url, committed_at, created_at FROM release_commits WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListReleaseCommitsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListReleaseCommits(ctx context.Context, arg ListReleaseCommitsParams) ([]ReleaseCommit, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseCommits, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseCommit{}
	for rows.Next() {
		var i ReleaseCommit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleaseVersion,
			&i.CommitSha,
			&i.CommitUrl,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReleaseCommit = `-- name: UpsertReleaseCommit :one
INSERT INTO release_commits (project_id, release_version, commit_sha, commit_url, committed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, release_version) DO UPDATE
SET commit_sha = EXCLUDED.commit_sha, commit_url = EXCLUDED.commit_url, committed_at = EXCLUDED.committed_at
RETURNING id, project_id, release_version, commit_sha, commit_url, committed_at, created_at
`

type UpsertReleaseCommitParams struct {
	ProjectID      uuid.UUID      `json:"project_id"`
	ReleaseVersion string         `json:"release_version"`
	CommitSha      string         `json:"commit_sha"`
	CommitUrl      sql.NullString `json:"commit_url"`
	CommittedAt    sql.NullTime   `json:"committed_at"`
}

func (q *Queries) UpsertReleaseCommit(ctx context.Context, arg UpsertReleaseCommitParams) (ReleaseCommit, error) {
	row := q.db.QueryRowContext(ctx, upsertReleaseCommit,
		arg.ProjectID,
		arg.ReleaseVersion,
		arg.CommitSha,
		arg.CommitUrl,
		arg.CommittedAt,
	)
	var i ReleaseCommit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseVersion,
		&i.CommitSha,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}
