// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addIssueTag = `-- name: AddIssueTag :exec
INSERT INTO issue_tags (issue_id, key, value) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddIssueTagParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	Key     string    `json:"key"`
	Value   string    `json:"value"`
}

func (q *Queries) AddIssueTag(ctx context.Context, arg AddIssueTagParams) error {
	_, err := q.db.ExecContext(ctx, addIssueTag, arg.IssueID, arg.Key, arg.Value)
	return err
}

const createTagRule = `-- name: CreateTagRule :one
INSERT INTO tag_rules (project_id, name, pattern, tag_key, tag_value, enabled, conditions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, pattern, tag_key, tag_value, enabled, created_at, updated_at, conditions
`

type CreateTagRuleParams struct {
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	Pattern    string                `json:"pattern"`
	TagKey     string                `json:"tag_key"`
	TagValue   string                `json:"tag_value"`
	Enabled    bool                  `json:"enabled"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) CreateTagRule(ctx context.Context, arg CreateTagRuleParams) (TagRule, error) {
	row := q.db.QueryRowContext(ctx, createTagRule,
		arg.ProjectID,
		arg.Name,
		arg.Pattern,
		arg.TagKey,
		arg.TagValue,
		arg.Enabled,
		arg.Conditions,
	)
	var i TagRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Pattern,
		&i.TagKey,
		&i.TagValue,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}

const deleteTagRule = `-- name: DeleteTagRule :exec
DELETE FROM tag_rules WHERE id = $1 AND project_id = $2
`

type DeleteTagRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteTagRule(ctx context.Context, arg DeleteTagRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteTagRule, arg.ID, arg.ProjectID)
	return err
}

const listDistinctTags = `-- name: ListDistinctTags :many
SELECT DISTINCT key, value FROM issue_tags
WHERE issue_id IN (SELECT id FROM issues WHERE project_id = $1)
ORDER BY key, value
`

type ListDistinctTagsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListDistinctTags(ctx context.Context, projectID uuid.UUID) ([]ListDistinctTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctTags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctTagsRow{}
	for rows.Next() {
		var i ListDistinctTagsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTagRules = `-- name: ListEnabledTagRules :many
SELECT id, project_id, name, pattern, tag_key, tag_value, enabled, created_at, updated_at, conditions FROM tag_rules WHERE project_id = $1 AND enabled = true
`

func (q *Queries) ListEnabledTagRules(ctx context.Context, projectID uuid.UUID) ([]TagRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTagRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagRule{}
	for rows.Next() {
		var i TagRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Pattern,
			&i.TagKey,
			&i.TagValue,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueIDsByTag = `-- name: ListIssueIDsByTag :many
SELECT issue_id FROM issue_tags WHERE key = $1 AND value = $2
`

type ListIssueIDsByTagParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListIssueIDsByTag(ctx context.Context, arg ListIssueIDsByTagParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listIssueIDsByTag, arg.Key, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var issue_id uuid.UUID
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueTags = `-- name: ListIssueTags :many
SELECT id, issue_id, key, value, created_at FROM issue_tags WHERE issue_id = $1 ORDER BY key, value
`

func (q *Queries) ListIssueTags(ctx context.Context, issueID uuid.UUID) ([]IssueTag, error) {
	rows, err := q.db.QueryContext(ctx, listIssueTags, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueTag{}
	for rows.Next() {
		var i IssueTag
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagRules = `-- name: ListTagRules :many
SELECT id, project_id, name, pattern, tag_key, tag_value, enabled, created_at, updated_at, conditions FROM tag_rules WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListTagRules(ctx context.Context, projectID uuid.UUID) ([]TagRule, error) {
	rows, err := q.db.QueryContext(ctx, listTagRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagRule{}
	for rows.Next() {
		var i TagRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Pattern,
			&i.TagKey,
			&i.TagValue,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByIssueIDs = `-- name: ListTagsByIssueIDs :many
SELECT id, issue_id, key, value, created_at FROM issue_tags WHERE issue_id = ANY($1::uuid[]) ORDER BY key, value
`

func (q *Queries) ListTagsByIssueIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]IssueTag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByIssueIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueTag{}
	for rows.Next() {
		var i IssueTag
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIssueTag = `-- name: RemoveIssueTag :exec
DELETE FROM issue_tags WHERE issue_id = $1 AND key = $2 AND value = $3
`

type RemoveIssueTagParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	Key     string    `json:"key"`
	Value   string    `json:"value"`
}

func (q *Queries) RemoveIssueTag(ctx context.Context, arg RemoveIssueTagParams) error {
	_, err := q.db.ExecContext(ctx, removeIssueTag, arg.IssueID, arg.Key, arg.Value)
	return err
}

const updateTagRule = `-- name: UpdateTagRule :one
UPDATE tag_rules
SET name = $3, pattern = $4, tag_key = $5, tag_value = $6, enabled = $7, conditions = $8, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, pattern, tag_key, tag_value, enabled, created_at, updated_at, conditions
`

type UpdateTagRuleParams struct {
	ID         uuid.UUID             `json:"id"`
	ProjectID  uuid.UUID             `json:"project_id"`
	Name       string                `json:"name"`
	Pattern    string                `json:"pattern"`
	TagKey     string                `json:"tag_key"`
	TagValue   string                `json:"tag_value"`
	Enabled    bool                  `json:"enabled"`
	Conditions pqtype.NullRawMessage `json:"conditions"`
}

func (q *Queries) UpdateTagRule(ctx context.Context, arg UpdateTagRuleParams) (TagRule, error) {
	row := q.db.QueryRowContext(ctx, updateTagRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Pattern,
		arg.TagKey,
		arg.TagValue,
		arg.Enabled,
		arg.Conditions,
	)
	var i TagRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Pattern,
		&i.TagKey,
		&i.TagValue,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conditions,
	)
	return i, err
}
