// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countTicketsByProject = `-- name: CountTicketsByProject :one
SELECT count(*) FROM tickets
WHERE project_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountTicketsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
}

func (q *Queries) CountTicketsByProject(ctx context.Context, arg CountTicketsByProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByProject, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsByStatus = `-- name: CountTicketsByStatus :many
SELECT status, count(*)::int AS count
FROM tickets
WHERE project_id = $1
GROUP BY status
`

type CountTicketsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountTicketsByStatus(ctx context.Context, projectID uuid.UUID) ([]CountTicketsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTicketsByStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTicketsByStatusRow{}
	for rows.Next() {
		var i CountTicketsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (issue_id, project_id, status, assigned_to, created_by, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at
`

type CreateTicketParams struct {
	IssueID    uuid.UUID     `json:"issue_id"`
	ProjectID  uuid.UUID     `json:"project_id"`
	Status     string        `json:"status"`
	AssignedTo uuid.NullUUID `json:"assigned_to"`
	CreatedBy  uuid.UUID     `json:"created_by"`
	Priority   int32         `json:"priority"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.IssueID,
		arg.ProjectID,
		arg.Status,
		arg.AssignedTo,
		arg.CreatedBy,
		arg.Priority,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByIssue = `-- name: GetTicketByIssue :one
SELECT id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at FROM tickets WHERE issue_id = $1 AND status NOT IN ('done', 'wontfix') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetTicketByIssue(ctx context.Context, issueID uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByIssue, issueID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByIssueIncludingDone = `-- name: GetTicketByIssueIncludingDone :one
SELECT id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at FROM tickets WHERE issue_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetTicketByIssueIncludingDone(ctx context.Context, issueID uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByIssueIncludingDone, issueID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByProject = `-- name: ListTicketsByProject :many
SELECT t.id, t.issue_id, t.project_id, t.status, t.assigned_to, t.created_by, t.priority, t.due_date, t.resolution_type, t.resolution_notes, t.fix_reference, t.title, t.description, t.escalated_system, t.escalated_key, t.escalated_url, t.created_at, t.updated_at, i.title AS issue_title, i.level AS issue_level, i.event_count AS issue_event_count,
       i.first_seen AS issue_first_seen, i.last_seen AS issue_last_seen,
       u.name AS assignee_name, u.email AS assignee_email, u.avatar_url AS assignee_avatar
FROM tickets t
JOIN issues i ON i.id = t.issue_id
LEFT JOIN users u ON u.id = t.assigned_to
WHERE t.project_id = $1
  AND ($2::text = '' OR t.status = $2::text)
ORDER BY
    CASE t.priority WHEN 90 THEN 0 WHEN 70 THEN 1 WHEN 50 THEN 2 ELSE 3 END,
    t.updated_at DESC
LIMIT $3 OFFSET $4
`

type ListTicketsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListTicketsByProjectRow struct {
	ID              uuid.UUID      `json:"id"`
	IssueID         uuid.UUID      `json:"issue_id"`
	ProjectID       uuid.UUID      `json:"project_id"`
	Status          string         `json:"status"`
	AssignedTo      uuid.NullUUID  `json:"assigned_to"`
	CreatedBy       uuid.UUID      `json:"created_by"`
	Priority        int32          `json:"priority"`
	DueDate         sql.NullTime   `json:"due_date"`
	ResolutionType  sql.NullString `json:"resolution_type"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	FixReference    sql.NullString `json:"fix_reference"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	EscalatedSystem sql.NullString `json:"escalated_system"`
	EscalatedKey    sql.NullString `json:"escalated_key"`
	EscalatedUrl    sql.NullString `json:"escalated_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	IssueTitle      string         `json:"issue_title"`
	IssueLevel      string         `json:"issue_level"`
	IssueEventCount int32          `json:"issue_event_count"`
	IssueFirstSeen  time.Time      `json:"issue_first_seen"`
	IssueLastSeen   time.Time      `json:"issue_last_seen"`
	AssigneeName    sql.NullString `json:"assignee_name"`
	AssigneeEmail   sql.NullString `json:"assignee_email"`
	AssigneeAvatar  sql.NullString `json:"assignee_avatar"`
}

func (q *Queries) ListTicketsByProject(ctx context.Context, arg ListTicketsByProjectParams) ([]ListTicketsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsByProjectRow{}
	for rows.Next() {
		var i ListTicketsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProjectID,
			&i.Status,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.Priority,
			&i.DueDate,
			&i.ResolutionType,
			&i.ResolutionNotes,
			&i.FixReference,
			&i.Title,
			&i.Description,
			&i.EscalatedSystem,
			&i.EscalatedKey,
			&i.EscalatedUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssueTitle,
			&i.IssueLevel,
			&i.IssueEventCount,
			&i.IssueFirstSeen,
			&i.IssueLastSeen,
			&i.AssigneeName,
			&i.AssigneeEmail,
			&i.AssigneeAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets SET
    status = $2,
    assigned_to = $3,
    priority = $4,
    due_date = $5,
    resolution_type = $6,
    resolution_notes = $7,
    fix_reference = $8,
    title = $9,
    description = $10,
    escalated_system = $11,
    escalated_key = $12,
    escalated_url = $13,
    updated_at = now()
WHERE id = $1
RETURNING id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at
`

type UpdateTicketParams struct {
	ID              uuid.UUID      `json:"id"`
	Status          string         `json:"status"`
	AssignedTo      uuid.NullUUID  `json:"assigned_to"`
	Priority        int32          `json:"priority"`
	DueDate         sql.NullTime   `json:"due_date"`
	ResolutionType  sql.NullString `json:"resolution_type"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	FixReference    sql.NullString `json:"fix_reference"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	EscalatedSystem sql.NullString `json:"escalated_system"`
	EscalatedKey    sql.NullString `json:"escalated_key"`
	EscalatedUrl    sql.NullString `json:"escalated_url"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.ID,
		arg.Status,
		arg.AssignedTo,
		arg.Priority,
		arg.DueDate,
		arg.ResolutionType,
		arg.ResolutionNotes,
		arg.FixReference,
		arg.Title,
		arg.Description,
		arg.EscalatedSystem,
		arg.EscalatedKey,
		arg.EscalatedUrl,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, issue_id, project_id, status, assigned_to, created_by, priority, due_date, resolution_type, resolution_notes, fix_reference, title, description, escalated_system, escalated_key, escalated_url, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicketStatus, arg.ID, arg.Status)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Priority,
		&i.DueDate,
		&i.ResolutionType,
		&i.ResolutionNotes,
		&i.FixReference,
		&i.Title,
		&i.Description,
		&i.EscalatedSystem,
		&i.EscalatedKey,
		&i.EscalatedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
