// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users SET status = 'active', name = $2, google_id = $3, avatar_url = $4, updated_at = now()
WHERE id = $1
RETURNING id, email, name, role, google_id, avatar_url, created_at, updated_at, status
`

type ActivateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	GoogleID  sql.NullString `json:"google_id"`
	AvatarUrl string         `json:"avatar_url"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, activateUser,
		arg.ID,
		arg.Name,
		arg.GoogleID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (email, role, status)
VALUES ($1, $2, 'invited')
RETURNING id, email, name, role, google_id, avatar_url, created_at, updated_at, status
`

type CreateInvitedUserParams struct {
	Email string `json:"email"`
	Role  string `json:"role"`
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createInvitedUser, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, google_id, avatar_url, created_at, updated_at, status FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, google_id, avatar_url, created_at, updated_at, status FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getUserByNameOrEmail = `-- name: GetUserByNameOrEmail :one
SELECT id, email, name, role, google_id, avatar_url, created_at, updated_at, status FROM users WHERE (name = $1 OR email = $1) AND status = 'active'
`

func (q *Queries) GetUserByNameOrEmail(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByNameOrEmail, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, google_id, avatar_url, created_at, updated_at, status FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, name, role, google_id, avatar_url, created_at, updated_at, status
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, name, role, google_id, avatar_url, created_at, updated_at, status
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const upsertUserByGoogle = `-- name: UpsertUserByGoogle :one
INSERT INTO users (email, name, google_id, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name, google_id = EXCLUDED.google_id, avatar_url = EXCLUDED.avatar_url, updated_at = now()
RETURNING id, email, name, role, google_id, avatar_url, created_at, updated_at, status
`

type UpsertUserByGoogleParams struct {
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	GoogleID  sql.NullString `json:"google_id"`
	AvatarUrl string         `json:"avatar_url"`
}

func (q *Queries) UpsertUserByGoogle(ctx context.Context, arg UpsertUserByGoogleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByGoogle,
		arg.Email,
		arg.Name,
		arg.GoogleID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
